// client/src/components/UserManagement.jsx
import React, { useState, useEffect } from 'react'
import { Plus, Edit2, Trash2, UserPlus, Upload, Search, ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react'
import axios from 'axios'
import ConfirmDialog from './ConfirmDialog'

const UserManagement = ({ onUpdate }) => {
  const [users, setUsers] = useState([])
  const [showModal, setShowModal] = useState(false)
  const [showImportModal, setShowImportModal] = useState(false)
  const [editingUser, setEditingUser] = useState(null)
  const [csvFile, setCsvFile] = useState(null)
  const [importing, setImporting] = useState(false)
  const [importResult, setImportResult] = useState(null)
  const [deleteConfirm, setDeleteConfirm] = useState({ isOpen: false, userId: null, userName: '' })
  const [searchQuery, setSearchQuery] = useState('')
  const [currentPage, setCurrentPage] = useState(1)
  const [itemsPerPage] = useState(20)
  const [refreshing, setRefreshing] = useState(false)
  const [formData, setFormData] = useState({
    employeeId: '',
    name: '',
    email: '',
    password: '',
    role: 'sales',
    isActive: true
  })
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    fetchUsers()
  }, [])

  const fetchUsers = async () => {
    try {
      setRefreshing(true)
      const response = await axios.get('/api/users')
      setUsers(response.data)
    } catch (error) {
      console.error('Error fetching users:', error)
    } finally {
      setRefreshing(false)
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)

    try {
      if (editingUser) {
        await axios.put(`/api/users/${editingUser._id}`, formData)
      } else {
        await axios.post('/api/users', formData)
      }
      
      fetchUsers()
      onUpdate()
      setShowModal(false)
      resetForm()
    } catch (error) {
      console.error('Error saving user:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async () => {
    try {
      await axios.delete(`/api/users/${deleteConfirm.userId}`)
      fetchUsers()
      onUpdate()
    } catch (error) {
      console.error('Error deleting user:', error)
    }
  }

  const handleCsvImport = async (e) => {
    e.preventDefault()
    if (!csvFile) return

    setImporting(true)
    setImportResult(null)

    const formData = new FormData()
    formData.append('csvFile', csvFile)

    try {
      const response = await axios.post('/api/users/import', formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      })
      
      setImportResult(response.data)
      fetchUsers()
      onUpdate()
      setCsvFile(null)
      
      setTimeout(() => {
        setShowImportModal(false)
        setImportResult(null)
      }, 3000)
    } catch (error) {
      console.error('Error importing CSV:', error)
      setImportResult({
        success: 0,
        failed: 0,
        errors: [error.response?.data?.message || 'Failed to import CSV']
      })
    } finally {
      setImporting(false)
    }
  }

  const resetForm = () => {
    setFormData({ employeeId: '', name: '', email: '', password: '', role: 'sales', isActive: true })
    setEditingUser(null)
  }

  const openModal = (user = null) => {
    if (user) {
      setFormData({
        employeeId: user.employeeId || '',
        name: user.name,
        email: user.email,
        password: '',
        role: user.role,
        isActive: user.isActive !== undefined ? user.isActive : true
      })
      setEditingUser(user)
    } else {
      resetForm()
    }
    setShowModal(true)
  }

  // Filter and paginate users
  const filteredUsers = users.filter(user => {
    const searchLower = searchQuery.toLowerCase()
    return (
      user.name.toLowerCase().includes(searchLower) ||
      user.email.toLowerCase().includes(searchLower) ||
      (user.employeeId && user.employeeId.toLowerCase().includes(searchLower)) ||
      user.role.toLowerCase().includes(searchLower)
    )
  })

  const totalPages = Math.ceil(filteredUsers.length / itemsPerPage)
  const startIndex = (currentPage - 1) * itemsPerPage
  const endIndex = startIndex + itemsPerPage
  const paginatedUsers = filteredUsers.slice(startIndex, endIndex)

  // Reset to page 1 when search changes
  useEffect(() => {
    setCurrentPage(1)
  }, [searchQuery])

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Employee Members</h2>
        <div className="flex space-x-3">
          <button
            onClick={fetchUsers}
            disabled={refreshing}
            className="flex items-center px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            title="Refresh employees"
          >
            <RefreshCw className={`h-4 w-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
            Refresh
          </button>
          <button
            onClick={() => setShowImportModal(true)}
            className="flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
          >
            <Upload className="h-4 w-4 mr-2" />
            Import CSV
          </button>
          <button
            onClick={() => openModal()}
            className="flex items-center px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
          >
            <Plus className="h-4 w-4 mr-2" />
            Add Employee
          </button>
        </div>
      </div>

      {/* Search Bar */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
        <input
          type="text"
          placeholder="Search employees by name, email, employee ID, or role..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
        />
      </div>

      {/* Table with hidden scrollbar */}
      <div className="overflow-x-auto scrollbar-hide">
        <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead className="bg-gray-50 dark:bg-gray-700">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Employee ID
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Name
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Email
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Role
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Status
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
            {paginatedUsers.length > 0 ? (
              paginatedUsers.map((user) => (
                <tr key={user._id}>
                  <td className="px-6 py-4 whitespace-nowrap">
                    {user.employeeId ? (
                      <span className="px-2 py-1 text-xs font-mono bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-white rounded">
                        {user.employeeId}
                      </span>
                    ) : (
                      <span className="text-xs text-gray-400 dark:text-gray-500 italic">N/A</span>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                    <div className="flex items-center">
                      {user.name}
                      {user.isSystemAdmin && (
                        <span className="ml-2 px-2 py-0.5 text-xs bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-200 rounded border border-purple-300 dark:border-purple-700" title="System admin account - cannot be deleted">
                          System
                        </span>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                    {user.email}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 text-xs rounded-full ${
                      user.role === 'admin' 
                        ? 'bg-purple-100 dark:bg-purple-900/20 text-purple-800 dark:text-purple-200'
                        : 'bg-blue-100 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200'
                    }`}>
                      {user.role.charAt(0).toUpperCase() + user.role.slice(1)}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 text-xs rounded-full ${
                      user.isActive 
                        ? 'bg-green-100 dark:bg-green-900/20 text-green-800 dark:text-green-200'
                        : 'bg-red-100 dark:bg-red-900/20 text-red-800 dark:text-red-200'
                    }`}>
                      {user.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex space-x-2">
                      <button
                        onClick={() => openModal(user)}
                        className="text-primary-600 dark:text-primary-400 hover:text-primary-900 dark:hover:text-primary-300"
                        title="Edit user"
                      >
                        <Edit2 className="h-4 w-4" />
                      </button>
                      {!user.isSystemAdmin ? (
                        <button
                          onClick={() => setDeleteConfirm({ 
                            isOpen: true, 
                            userId: user._id, 
                            userName: user.name 
                          })}
                          className="text-red-600 dark:text-red-400 hover:text-red-900 dark:hover:text-red-300"
                          title="Delete user"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      ) : (
                        <button
                          disabled
                          className="text-gray-400 dark:text-gray-600 cursor-not-allowed"
                          title="System admin cannot be deleted"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={6} className="px-6 py-8 text-center text-sm text-gray-500 dark:text-gray-400">
                  {searchQuery ? 'No employees found matching your search' : 'No employees yet'}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between border-t border-gray-200 dark:border-gray-700 pt-4">
          <div className="text-sm text-gray-700 dark:text-gray-300">
            Showing {startIndex + 1} to {Math.min(endIndex, filteredUsers.length)} of {filteredUsers.length} employees
          </div>
          <div className="flex space-x-2">
            <button
              onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
              disabled={currentPage === 1}
              className="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <ChevronLeft className="h-4 w-4" />
            </button>
            <span className="px-4 py-1 text-sm font-medium text-gray-700 dark:text-gray-300">
              Page {currentPage} of {totalPages}
            </span>
            <button
              onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
              disabled={currentPage === totalPages}
              className="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      )}

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
              {editingUser ? 'Edit Employee' : 'Add Employee'}
            </h3>
            
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Name *
                </label>
                <input
                  type="text"
                  required
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Enter employee name"
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Email *
                </label>
                <input
                  type="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="employee@example.com"
                  disabled={editingUser}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white disabled:opacity-50 disabled:cursor-not-allowed"
                />
                {editingUser && (
                  <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Email cannot be changed</p>
                )}
              </div>

              {!editingUser && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Password *
                  </label>
                  <input
                    type="password"
                    required={!editingUser}
                    value={formData.password}
                    onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                    placeholder="Enter password"
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                  />
                </div>
              )}
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Role
                </label>
                <select
                  value={formData.role}
                  onChange={(e) => setFormData({ ...formData, role: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="sales">Sales</option>
                  <option value="admin">Admin</option>
                </select>
                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                  {formData.role === 'admin' ? 'Admin users do not require an Employee ID' : 'Sales users require an Employee ID'}
                </p>
              </div>
              
              {formData.role === 'sales' && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Employee ID *
                  </label>
                  <input
                    type="text"
                    required
                    value={formData.employeeId}
                    onChange={(e) => setFormData({ ...formData, employeeId: e.target.value.toUpperCase() })}
                    placeholder="e.g. VIB_001"
                    disabled={editingUser}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                  {editingUser && (
                    <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Employee ID cannot be changed</p>
                  )}
                </div>
              )}

              {editingUser && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Status
                  </label>
                  <select
                    value={formData.isActive ? 'active' : 'inactive'}
                    onChange={(e) => setFormData({ ...formData, isActive: e.target.value === 'active' })}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                  </select>
                  <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                    {formData.isActive ? 'Employee can log in and access the system' : 'Employee cannot log in (account disabled)'}
                  </p>
                </div>
              )}
              
              <div className="flex justify-end space-x-3 pt-4">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50"
                >
                  {loading ? 'Saving...' : editingUser ? 'Update' : 'Create'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* CSV Import Modal */}
      {showImportModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-lg">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
              Import Employees from CSV
            </h3>
            
            <form onSubmit={handleCsvImport} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  CSV File
                </label>
                <div className="relative">
                  <input
                    type="file"
                    accept=".csv"
                    onChange={(e) => setCsvFile(e.target.files[0])}
                    className="hidden"
                    id="user-csv-file-input"
                    required
                  />
                  <label
                    htmlFor="user-csv-file-input"
                    className="flex items-center justify-center w-full px-4 py-3 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg cursor-pointer hover:border-primary-500 dark:hover:border-primary-400 transition-colors bg-gray-50 dark:bg-gray-700/50"
                  >
                    <Upload className="h-5 w-5 text-gray-400 dark:text-gray-500 mr-2" />
                    <span className="text-sm text-gray-600 dark:text-gray-400">
                      {csvFile ? csvFile.name : 'Choose CSV file or drag here'}
                    </span>
                  </label>
                </div>
                <p className="mt-2 text-xs text-gray-500 dark:text-gray-400">
                  CSV should have columns: employeeId, name, email, password, role (admin or sales)
                </p>
              </div>

              {importResult && (
                <div className={`p-4 rounded-md ${importResult.errors?.length > 0 ? 'bg-yellow-50 dark:bg-yellow-900/20' : 'bg-green-50 dark:bg-green-900/20'}`}>
                  <p className="text-sm font-medium text-gray-900 dark:text-white">
                    Import Results:
                  </p>
                  <p className="text-sm text-gray-700 dark:text-gray-300">
                    Successfully imported: {importResult.success || 0}
                  </p>
                  {importResult.failed > 0 && (
                    <p className="text-sm text-gray-700 dark:text-gray-300">
                      Failed: {importResult.failed}
                    </p>
                  )}
                  {importResult.errors?.length > 0 && (
                    <div className="mt-2">
                      <p className="text-xs font-medium text-gray-700 dark:text-gray-300">Errors:</p>
                      <ul className="text-xs text-gray-600 dark:text-gray-400 list-disc list-inside">
                        {importResult.errors.slice(0, 5).map((err, idx) => (
                          <li key={idx}>{err}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
              
              <div className="flex justify-end space-x-3 pt-4">
                <button
                  type="button"
                  onClick={() => {
                    setShowImportModal(false)
                    setCsvFile(null)
                    setImportResult(null)
                  }}
                  className="px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
                  disabled={importing}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={importing || !csvFile}
                  className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
                >
                  {importing ? 'Importing...' : 'Import'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={deleteConfirm.isOpen}
        onClose={() => setDeleteConfirm({ isOpen: false, userId: null, userName: '' })}
        onConfirm={handleDelete}
        title="Delete Employee"
        message={`Are you sure you want to delete "${deleteConfirm.userName}"? This action cannot be undone.`}
        confirmText="Delete"
        cancelText="Cancel"
        variant="danger"
      />
    </div>
  )
}

export default UserManagement

// client-new/src/app/features/user-management/user-management.component.ts
import { Component, inject, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { EmployeeUser } from '../../models';
import { ConfirmDialogComponent } from '../../shared/confirm-dialog/confirm-dialog.component';

@Component({
  selector: 'app-user-management',
  standalone: true,
  imports: [CommonModule, FormsModule, ConfirmDialogComponent],
  templateUrl: './user-management.component.html',
})
export class UserManagementComponent {
  private readonly http = inject(HttpClient);
  readonly statsChanged = output<void>();

  readonly users = signal<EmployeeUser[]>([]);
  readonly showModal = signal(false);
  readonly showImportModal = signal(false);
  readonly editingUser = signal<EmployeeUser | null>(null);
  readonly deleteConfirm = signal({ isOpen: false, userId: '' as string | null, userName: '' });
  readonly searchQuery = signal('');
  readonly currentPage = signal(1);
  readonly itemsPerPage = 20;
  readonly refreshing = signal(false);
  readonly loading = signal(false);
  readonly csvFile = signal<File | null>(null);
  readonly importing = signal(false);
  readonly importResult = signal<{ success?: number; failed?: number; errors?: string[] } | null>(null);

  formData = { employeeId: '', name: '', email: '', password: '', role: 'sales', isActive: true };

  constructor() {
    void this.fetchUsers();
  }

  async fetchUsers(): Promise<void> {
    this.refreshing.set(true);
    try {
      const res = await firstValueFrom(this.http.get<EmployeeUser[]>('/api/users'));
      this.users.set(res);
    } catch (e) {
      console.error(e);
    } finally {
      this.refreshing.set(false);
    }
  }

  filteredUsers(): EmployeeUser[] {
    const q = this.searchQuery().toLowerCase();
    return this.users().filter(
      (u) =>
        u.name.toLowerCase().includes(q) ||
        u.email.toLowerCase().includes(q) ||
        (u.employeeId && u.employeeId.toLowerCase().includes(q)) ||
        u.role.toLowerCase().includes(q),
    );
  }

  paginatedUsers(): EmployeeUser[] {
    const f = this.filteredUsers();
    const start = (this.currentPage() - 1) * this.itemsPerPage;
    return f.slice(start, start + this.itemsPerPage);
  }

  totalPages(): number {
    return Math.max(1, Math.ceil(this.filteredUsers().length / this.itemsPerPage));
  }

  openModal(user: EmployeeUser | null = null): void {
    if (user) {
      this.editingUser.set(user);
      this.formData = {
        employeeId: user.employeeId || '',
        name: user.name,
        email: user.email,
        password: '',
        role: user.role,
        isActive: user.isActive !== false,
      };
    } else {
      this.editingUser.set(null);
      this.formData = { employeeId: '', name: '', email: '', password: '', role: 'sales', isActive: true };
    }
    this.showModal.set(true);
  }

  async saveUser(e: Event): Promise<void> {
    e.preventDefault();
    this.loading.set(true);
    try {
      const ed = this.editingUser();
      if (ed) {
        await firstValueFrom(this.http.put(`/api/users/${ed._id}`, this.formData));
      } else {
        await firstValueFrom(this.http.post('/api/users', this.formData));
      }
      await this.fetchUsers();
      this.statsChanged.emit();
      this.showModal.set(false);
    } catch (err) {
      console.error(err);
    } finally {
      this.loading.set(false);
    }
  }

  async deleteUser(): Promise<void> {
    const d = this.deleteConfirm();
    if (!d.userId) return;
    try {
      await firstValueFrom(this.http.delete(`/api/users/${d.userId}`));
      await this.fetchUsers();
      this.statsChanged.emit();
    } catch (e) {
      console.error(e);
    } finally {
      this.deleteConfirm.set({ isOpen: false, userId: null, userName: '' });
    }
  }

  async importCsv(e: Event): Promise<void> {
    e.preventDefault();
    const f = this.csvFile();
    if (!f) return;
    this.importing.set(true);
    this.importResult.set(null);
    const fd = new FormData();
    fd.append('csvFile', f);
    try {
      const res = await firstValueFrom(
        this.http.post<{ success?: number; failed?: number; errors?: string[] }>('/api/users/import', fd),
      );
      this.importResult.set(res);
      await this.fetchUsers();
      this.statsChanged.emit();
      this.csvFile.set(null);
      setTimeout(() => {
        this.showImportModal.set(false);
        this.importResult.set(null);
      }, 3000);
    } catch (err: unknown) {
      this.importResult.set({
        success: 0,
        failed: 0,
        errors: [(err as { error?: { message?: string } })?.error?.message || 'Failed to import CSV'],
      });
    } finally {
      this.importing.set(false);
    }
  }

  onSearchChange(): void {
    this.currentPage.set(1);
  }

  prevPage(): void {
    this.currentPage.update((p) => Math.max(1, p - 1));
  }

  nextPage(): void {
    this.currentPage.update((p) => Math.min(this.totalPages(), p + 1));
  }
}

<div class="space-y-6">
  <div class="flex justify-between items-center">
    <h2 class="text-lg font-semibold text-gray-900 dark:text-white">Employee Members</h2>
    <div class="flex space-x-3">
      <button
        type="button"
        (click)="fetchUsers()"
        [disabled]="refreshing()"
        class="flex items-center px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
        title="Refresh employees"
      >
        <svg class="h-4 w-4 mr-2" [class.animate-spin]="refreshing()" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/>
        </svg>
        Refresh
      </button>
      <button
        type="button"
        (click)="showImportModal.set(true)"
        class="flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
      >
        <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
        </svg>
        Import CSV
      </button>
      <button
        type="button"
        (click)="openModal(null)"
        class="flex items-center px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
      >
        <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
        </svg>
        Add Employee
      </button>
    </div>
  </div>

  <div class="relative">
    <svg class="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
    <input
      type="text"
      placeholder="Search employees by name, email, employee ID, or role..."
      [value]="searchQuery()"
      (input)="searchQuery.set($any($event.target).value); onSearchChange()"
      class="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
    />
  </div>

  <div class="overflow-x-auto scrollbar-hide">
    <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
      <thead class="bg-gray-50 dark:bg-gray-700">
        <tr>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Employee ID</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Name</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Email</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Role</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Status</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Actions</th>
        </tr>
      </thead>
      <tbody class="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
        @for (u of paginatedUsers(); track u._id) {
          <tr>
            <td class="px-6 py-4 whitespace-nowrap">
              @if (u.employeeId) {
                <span class="px-2 py-1 text-xs font-mono bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-white rounded">
                  {{ u.employeeId }}
                </span>
              } @else {
                <span class="text-xs text-gray-400 dark:text-gray-500 italic">N/A</span>
              }
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
              <div class="flex items-center">
                {{ u.name }}
                @if (u.isSystemAdmin) {
                  <span class="ml-2 px-2 py-0.5 text-xs bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-200 rounded border border-purple-300 dark:border-purple-700" title="System admin account - cannot be deleted">
                    System
                  </span>
                }
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{{ u.email }}</td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span
                class="px-2 py-1 text-xs rounded-full"
                [ngClass]="u.role === 'admin' ? 'bg-purple-100 dark:bg-purple-900/20 text-purple-800 dark:text-purple-200' : 'bg-blue-100 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200'"
              >
                {{ u.role.charAt(0).toUpperCase() + u.role.slice(1) }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span
                class="px-2 py-1 text-xs rounded-full"
                [ngClass]="u.isActive ? 'bg-green-100 dark:bg-green-900/20 text-green-800 dark:text-green-200' : 'bg-red-100 dark:bg-red-900/20 text-red-800 dark:text-red-200'"
              >
                {{ u.isActive ? 'Active' : 'Inactive' }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
              <div class="flex space-x-2">
                <button
                  type="button"
                  (click)="openModal(u)"
                  class="text-primary-600 dark:text-primary-400 hover:text-primary-900 dark:hover:text-primary-300"
                  title="Edit user"
                >
                  <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                  </svg>
                </button>
                @if (!u.isSystemAdmin) {
                  <button
                    type="button"
                    (click)="deleteConfirm.set({ isOpen: true, userId: u._id, userName: u.name })"
                    class="text-red-600 dark:text-red-400 hover:text-red-900 dark:hover:text-red-300"
                    title="Delete user"
                  >
                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                    </svg>
                  </button>
                } @else {
                  <button
                    type="button"
                    disabled
                    class="text-gray-400 dark:text-gray-600 cursor-not-allowed"
                    title="System admin cannot be deleted"
                  >
                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                    </svg>
                  </button>
                }
              </div>
            </td>
          </tr>
        } @empty {
          <tr>
            <td colspan="6" class="px-6 py-8 text-center text-sm text-gray-500 dark:text-gray-400">
              {{ searchQuery() ? 'No employees found matching your search' : 'No employees yet' }}
            </td>
          </tr>
        }
      </tbody>
    </table>
  </div>

  @if (totalPages() > 1) {
    <div class="flex items-center justify-between border-t border-gray-200 dark:border-gray-700 pt-4">
      <div class="text-sm text-gray-700 dark:text-gray-300">
        Showing {{ ((currentPage() - 1) * itemsPerPage) + 1 }} to {{ currentPage() * itemsPerPage < filteredUsers().length ? currentPage() * itemsPerPage : filteredUsers().length }} of {{ filteredUsers().length }} employees
      </div>
      <div class="flex space-x-2">
        <button
          type="button"
          (click)="prevPage()"
          [disabled]="currentPage() === 1"
          class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" /></svg>
        </button>
        <span class="px-4 py-1 text-sm font-medium text-gray-700 dark:text-gray-300">
          Page {{ currentPage() }} of {{ totalPages() }}
        </span>
        <button
          type="button"
          (click)="nextPage()"
          [disabled]="currentPage() === totalPages()"
          class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg>
        </button>
      </div>
    </div>
  }

  @if (showModal()) {
    <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div class="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-md">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">
          {{ editingUser() ? 'Edit Employee' : 'Add Employee' }}
        </h3>

        <form (ngSubmit)="saveUser($event)" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Name *</label>
            <input
              type="text"
              required
              [(ngModel)]="formData.name"
              name="name"
              placeholder="Enter employee name"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Email *</label>
            <input
              type="email"
              required
              [(ngModel)]="formData.email"
              name="email"
              placeholder="employee@example.com"
              [disabled]="!!editingUser()"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white disabled:opacity-50 disabled:cursor-not-allowed"
            />
            @if (editingUser()) {
              <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Email cannot be changed</p>
            }
          </div>

          @if (!editingUser()) {
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Password *</label>
              <input
                type="password"
                [required]="!editingUser()"
                [(ngModel)]="formData.password"
                name="pw"
                placeholder="Enter password"
                class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>
          }

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Role</label>
            <select
              [(ngModel)]="formData.role"
              name="role"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            >
              <option value="sales">Sales</option>
              <option value="admin">Admin</option>
            </select>
            <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
              {{ formData.role === 'admin' ? 'Admin users do not require an Employee ID' : 'Sales users require an Employee ID' }}
            </p>
          </div>

          @if (formData.role === 'sales') {
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Employee ID *</label>
              <input
                type="text"
                required
                [ngModel]="formData.employeeId"
                (ngModelChange)="formData.employeeId = ($event || '').toUpperCase()"
                name="eid"
                placeholder="e.g. VIB_001"
                [disabled]="!!editingUser()"
                class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white disabled:opacity-50 disabled:cursor-not-allowed"
              />
              @if (editingUser()) {
                <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Employee ID cannot be changed</p>
              }
            </div>
          }

          @if (editingUser()) {
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Status</label>
              <select
                [ngModel]="formData.isActive ? 'active' : 'inactive'"
                (ngModelChange)="formData.isActive = $event === 'active'"
                name="st"
                class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              >
                <option value="active">Active</option>
                <option value="inactive">Inactive</option>
              </select>
              <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
                {{ formData.isActive ? 'Employee can log in and access the system' : 'Employee cannot log in (account disabled)' }}
              </p>
            </div>
          }

          <div class="flex justify-end space-x-3 pt-4">
            <button
              type="button"
              (click)="showModal.set(false)"
              class="px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
            >
              Cancel
            </button>
            <button
              type="submit"
              [disabled]="loading()"
              class="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50"
            >
              {{ loading() ? 'Saving...' : editingUser() ? 'Update' : 'Create' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  }

  @if (showImportModal()) {
    <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div class="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-lg">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Import Employees from CSV</h3>

        <form (ngSubmit)="importCsv($event)" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">CSV File</label>
            <div class="relative">
              <input
                type="file"
                accept=".csv"
                (change)="csvFile.set($any($event.target).files?.[0] || null)"
                class="hidden"
                id="user-csv-file-input"
                required
              />
              <label
                for="user-csv-file-input"
                class="flex items-center justify-center w-full px-4 py-3 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg cursor-pointer hover:border-primary-500 dark:hover:border-primary-400 transition-colors bg-gray-50 dark:bg-gray-700/50"
              >
                <svg class="h-5 w-5 text-gray-400 dark:text-gray-500 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                </svg>
                <span class="text-sm text-gray-600 dark:text-gray-400">
                  {{ csvFile()?.name || 'Choose CSV file or drag here' }}
                </span>
              </label>
            </div>
            <p class="mt-2 text-xs text-gray-500 dark:text-gray-400">
              CSV should have columns: employeeId, name, email, password, role (admin or sales)
            </p>
          </div>

          @if (importResult()) {
            <div
              class="p-4 rounded-md"
              [ngClass]="importResult()!.errors?.length ? 'bg-yellow-50 dark:bg-yellow-900/20' : 'bg-green-50 dark:bg-green-900/20'"
            >
              <p class="text-sm font-medium text-gray-900 dark:text-white">Import Results:</p>
              <p class="text-sm text-gray-700 dark:text-gray-300">Successfully imported: {{ importResult()!.success || 0 }}</p>
              @if ((importResult()!.failed || 0) > 0) {
                <p class="text-sm text-gray-700 dark:text-gray-300">Failed: {{ importResult()!.failed }}</p>
              }
              @if (importResult()!.errors?.length) {
                <div class="mt-2">
                  <p class="text-xs font-medium text-gray-700 dark:text-gray-300">Errors:</p>
                  <ul class="text-xs text-gray-600 dark:text-gray-400 list-disc list-inside">
                    @for (err of importResult()!.errors!.slice(0, 5); track $index) {
                      <li>{{ err }}</li>
                    }
                  </ul>
                </div>
              }
            </div>
          }

          <div class="flex justify-end space-x-3 pt-4">
            <button
              type="button"
              (click)="showImportModal.set(false); csvFile.set(null); importResult.set(null)"
              class="px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
              [disabled]="importing()"
            >
              Cancel
            </button>
            <button
              type="submit"
              [disabled]="importing() || !csvFile()"
              class="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
            >
              {{ importing() ? 'Importing...' : 'Import' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  }

  <app-confirm-dialog
    [isOpen]="deleteConfirm().isOpen"
    (onClose)="deleteConfirm.set({ isOpen: false, userId: null, userName: '' })"
    (onConfirm)="deleteUser()"
    title="Delete Employee"
    [message]="'Are you sure you want to delete &quot;' + deleteConfirm().userName + '&quot;? This action cannot be undone.'"
    confirmText="Delete"
    cancelText="Cancel"
    variant="danger"
  />
</div>
