// client/src/components/Dashboard.jsx
import { useState, useEffect } from 'react'
import { useAuth } from '../contexts/AuthContext'
import UserManagement from './UserManagement'
import ClientManagement from './ClientManagement'
import Statistics from './Statistics'
import Reports from './Reports'
import UnassignedLeads from './UnassignedLeads'
import MappingManagement from './MappingManagement'
import BrandPartnerManagement from './BrandPartnerManagement'
import { Users, Phone, BarChart3, Clock, TrendingUp, Mail, X, Tag, AlertTriangle, Map, Building2 } from 'lucide-react'
import axios from 'axios'

const Dashboard = () => {
  const { user } = useAuth()
  const [activeTab, setActiveTab] = useState('clients')
  const [stats, setStats] = useState({
    totalLeads: 0,
    totalUsers: 0,
    pendingCalls: 0,
    completedCalls: 0,
    unassignedLeads: 0
  })
  const [showLeadsModal, setShowLeadsModal] = useState(false)
  const [leadsGroupedBySource, setLeadsGroupedBySource] = useState({})

  useEffect(() => {
    fetchStats()
  }, [])

  // Auto-redirect to unassigned leads if there are any
  useEffect(() => {
    if (user.role === 'admin' && stats.unassignedLeads > 0 && activeTab === 'clients') {
      setActiveTab('unassigned')
    }
  }, [stats.unassignedLeads, user.role])

  const fetchStats = async () => {
    try {
      const [clientsRes, usersRes] = await Promise.all([
        axios.get('/api/clients'),
        user.role === 'admin' ? axios.get('/api/users') : Promise.resolve({ data: [] })
      ])
      
      const leads = clientsRes.data
      const users = usersRes.data
      
      // Count unassigned leads
      const unassigned = leads.filter(l => l.isUnassigned === true).length
      
      // Group leads by source
      const grouped = leads.reduce((acc, lead) => {
        const source = lead.source || 'No Source'
        if (!acc[source]) {
          acc[source] = []
        }
        acc[source].push(lead)
        return acc
      }, {})
      setLeadsGroupedBySource(grouped)
      
      setStats({
        totalLeads: leads.length,
        totalUsers: users.length,
        pendingCalls: leads.filter(c => c.status === 'pending' || c.status === 'no-response' || c.status === 'follow-up').length,
        completedCalls: leads.filter(c => ['qualified', 'already-finalised', 'closed'].includes(c.status)).length,
        unassignedLeads: unassigned
      })
    } catch (error) {
      console.error('Error fetching stats:', error)
    }
  }

  const StatCard = ({ icon: Icon, title, value, color = 'primary', onClick }) => {
    const colorClasses = {
      primary: {
        bg: 'bg-blue-100 dark:bg-blue-900/20',
        icon: 'text-blue-600 dark:text-blue-400'
      },
      yellow: {
        bg: 'bg-yellow-100 dark:bg-yellow-900/20',
        icon: 'text-yellow-600 dark:text-yellow-400'
      },
      green: {
        bg: 'bg-green-100 dark:bg-green-900/20',
        icon: 'text-green-600 dark:text-green-400'
      }
    }

    const colors = colorClasses[color] || colorClasses.primary

    return (
      <div 
        className={`bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 ${
          onClick ? 'cursor-pointer hover:shadow-md transition-shadow' : ''
        }`}
        onClick={onClick}
      >
        <div className="flex items-center">
          <div className={`p-3 rounded-full ${colors.bg}`}>
            <Icon className={`h-6 w-6 ${colors.icon}`} />
          </div>
          <div className="ml-4">
            <p className="text-sm font-medium text-gray-600 dark:text-gray-400">{title}</p>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{value}</p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard 
          icon={Phone} 
          title="Total Leads" 
          value={stats.totalLeads} 
          onClick={() => setShowLeadsModal(true)}
        />
        {user.role === 'admin' && (
          <StatCard icon={Users} title="Employee Members" value={stats.totalUsers} />
        )}
        <StatCard icon={Clock} title="Pending Calls" value={stats.pendingCalls} color="yellow" />
        <StatCard icon={BarChart3} title="Completed" value={stats.completedCalls} color="green" />
      </div>

      {/* Leads Breakdown Modal */}
      {showLeadsModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white dark:bg-gray-800 rounded-lg w-full max-w-2xl shadow-lg">
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                  Total Leads Breakdown
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                  {stats.totalLeads} leads organized by source
                </p>
              </div>
              <button
                onClick={() => setShowLeadsModal(false)}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6">
              <div className="space-y-3">
                {Object.keys(leadsGroupedBySource).sort().map((source) => {
                  const sourceLeads = leadsGroupedBySource[source]
                  const percentage = ((sourceLeads.length / stats.totalLeads) * 100).toFixed(1)
                  
                  return (
                    <div 
                      key={source} 
                      className="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700 rounded-lg border border-gray-200 dark:border-gray-600"
                    >
                      <div className="flex items-center flex-1">
                        <Tag className="h-5 w-5 text-gray-600 dark:text-gray-400 mr-3" />
                        <div className="flex-1">
                          <h4 className="text-sm font-medium text-gray-900 dark:text-white">
                            {source}
                          </h4>
                          <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                            {percentage}% of total
                          </p>
                        </div>
                      </div>
                      <span className="text-lg font-bold text-gray-900 dark:text-white ml-4">
                        {sourceLeads.length}
                      </span>
                    </div>
                  )
                })}

                {Object.keys(leadsGroupedBySource).length === 0 && (
                  <div className="text-center py-8 text-gray-500 dark:text-gray-400">
                    No leads found
                  </div>
                )}
              </div>
            </div>

            {/* Footer */}
            <div className="flex items-center justify-between p-6 border-t border-gray-200 dark:border-gray-700">
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Total: {stats.totalLeads} leads from {Object.keys(leadsGroupedBySource).length} source{Object.keys(leadsGroupedBySource).length !== 1 ? 's' : ''}
              </p>
              <button
                onClick={() => setShowLeadsModal(false)}
                className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Navigation Tabs */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
        <div className="border-b border-gray-200 dark:border-gray-700">
          <nav className="flex space-x-8 px-6">
            {user.role === 'admin' && (
              <button
                onClick={() => setActiveTab('unassigned')}
                className={`py-4 px-1 border-b-2 font-medium text-sm relative ${
                  activeTab === 'unassigned'
                    ? 'border-primary-500 text-primary-600 dark:text-primary-400'
                    : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                }`}
              >
                <AlertTriangle className="h-4 w-4 inline mr-2" />
                Unassigned Leads
                {stats.unassignedLeads > 0 && (
                  <span className="ml-2 px-2 py-0.5 text-xs font-bold bg-orange-500 text-white rounded-full">
                    {stats.unassignedLeads}
                  </span>
                )}
              </button>
            )}
            
            <button
              onClick={() => setActiveTab('clients')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'clients'
                  ? 'border-primary-500 text-primary-600 dark:text-primary-400'
                  : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
              }`}
            >
              <Phone className="h-4 w-4 inline mr-2" />
              Leads
            </button>
            
            <button
              onClick={() => setActiveTab('statistics')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'statistics'
                  ? 'border-primary-500 text-primary-600 dark:text-primary-400'
                  : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
              }`}
            >
              <TrendingUp className="h-4 w-4 inline mr-2" />
              Statistics
            </button>
            
            {user.role === 'admin' && (
              <>
                <button
                  onClick={() => setActiveTab('users')}
                  className={`py-4 px-1 border-b-2 font-medium text-sm ${
                    activeTab === 'users'
                      ? 'border-primary-500 text-primary-600 dark:text-primary-400'
                      : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                  }`}
                >
                  <Users className="h-4 w-4 inline mr-2" />
                  Employee Management
                </button>
                
                <button
                  onClick={() => setActiveTab('mapping')}
                  className={`py-4 px-1 border-b-2 font-medium text-sm ${
                    activeTab === 'mapping'
                      ? 'border-primary-500 text-primary-600 dark:text-primary-400'
                      : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                  }`}
                >
                  <Map className="h-4 w-4 inline mr-2" />
                  Mapping Management
                </button>
                
                <button
                  onClick={() => setActiveTab('brandpartner')}
                  className={`py-4 px-1 border-b-2 font-medium text-sm ${
                    activeTab === 'brandpartner'
                      ? 'border-primary-500 text-primary-600 dark:text-primary-400'
                      : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                  }`}
                >
                  <Building2 className="h-4 w-4 inline mr-2" />
                  Brand Partner Management
                </button>
                
                <button
                  onClick={() => setActiveTab('reports')}
                  className={`py-4 px-1 border-b-2 font-medium text-sm ${
                    activeTab === 'reports'
                      ? 'border-primary-500 text-primary-600 dark:text-primary-400'
                      : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                  }`}
                >
                  <Mail className="h-4 w-4 inline mr-2" />
                  Reports
                </button>
              </>
            )}
          </nav>
        </div>

        <div className="p-3">
          {activeTab === 'unassigned' && user.role === 'admin' && <UnassignedLeads onProcessComplete={fetchStats} />}
          {activeTab === 'clients' && <ClientManagement onUpdate={fetchStats} onSwitchToUnassigned={() => setActiveTab('unassigned')} />}
          {activeTab === 'statistics' && <Statistics />}
          {activeTab === 'users' && user.role === 'admin' && <UserManagement onUpdate={fetchStats} />}
          {activeTab === 'mapping' && user.role === 'admin' && <MappingManagement />}
          {activeTab === 'brandpartner' && user.role === 'admin' && <BrandPartnerManagement />}
          {activeTab === 'reports' && user.role === 'admin' && <Reports />}
        </div>
      </div>
    </div>
  )
}

export default Dashboard

// client-new/src/app/pages/dashboard/dashboard.component.ts
import { Component, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth.service';
import { Client, EmployeeUser } from '../../models';
import { StatisticsComponent } from '../../features/statistics/statistics.component';
import { ReportsComponent } from '../../features/reports/reports.component';
import { CallHistoryComponent } from '../../features/call-history/call-history.component';
import { UserManagementComponent } from '../../features/user-management/user-management.component';
import { MappingManagementComponent } from '../../features/mapping-management/mapping-management.component';
import { UnassignedLeadsComponent } from '../../features/unassigned-leads/unassigned-leads.component';
import { ClientManagementComponent } from '../../features/client-management/client-management.component';
import { BrandPartnerManagementComponent } from '../../features/brand-partner/brand-partner-management.component';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    StatisticsComponent,
    ReportsComponent,
    CallHistoryComponent,
    UserManagementComponent,
    MappingManagementComponent,
    UnassignedLeadsComponent,
    ClientManagementComponent,
    BrandPartnerManagementComponent,
  ],
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
  private readonly http = inject(HttpClient);
  readonly auth = inject(AuthService);

  readonly activeTab = signal<string>('clients');
  readonly stats = signal({
    totalLeads: 0,
    totalUsers: 0,
    pendingCalls: 0,
    completedCalls: 0,
    unassignedLeads: 0,
  });
  readonly showLeadsModal = signal(false);
  readonly leadsGroupedBySource = signal<Record<string, Client[]>>({});

  readonly user = computed(() => this.auth.user());

  constructor() {
    void this.fetchStats();
  }

  async fetchStats(): Promise<void> {
    const u = this.user();
    if (!u) return;
    const prevUnassigned = this.stats().unassignedLeads;
    try {
      const clientsReq = firstValueFrom(this.http.get<Client[]>('/api/clients'));
      const usersReq =
        u.role === 'admin' ? firstValueFrom(this.http.get<EmployeeUser[]>('/api/users')) : Promise.resolve([] as EmployeeUser[]);
      const [leads, users] = await Promise.all([clientsReq, usersReq]);
      const unassigned = leads.filter((l) => l.isUnassigned === true).length;
      const grouped = leads.reduce<Record<string, Client[]>>((acc, lead) => {
        const source = lead.source || 'No Source';
        if (!acc[source]) acc[source] = [];
        acc[source].push(lead);
        return acc;
      }, {});
      this.leadsGroupedBySource.set(grouped);
      this.stats.set({
        totalLeads: leads.length,
        totalUsers: users.length,
        pendingCalls: leads.filter((c) => c.status === 'pending' || c.status === 'no-response' || c.status === 'follow-up').length,
        completedCalls: leads.filter((c) => ['qualified', 'already-finalised', 'closed'].includes(c.status)).length,
        unassignedLeads: unassigned,
      });
      // Match legacy client: only auto-switch when unassigned count *changes* (see Dashboard.jsx deps).
      if (u.role === 'admin' && unassigned > 0 && this.activeTab() === 'clients' && unassigned !== prevUnassigned) {
        this.activeTab.set('unassigned');
      }
    } catch (e) {
      console.error(e);
    }
  }

  sourceKeys(): string[] {
    return Object.keys(this.leadsGroupedBySource()).sort();
  }

  pctForSource(source: string): string {
    const total = this.stats().totalLeads;
    if (!total) return '0';
    const n = this.leadsGroupedBySource()[source]?.length ?? 0;
    return ((n / total) * 100).toFixed(1);
  }
}

<div class="space-y-6">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    <div
      class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 cursor-pointer hover:shadow-md transition-shadow"
      (click)="showLeadsModal.set(true)"
    >
      <div class="flex items-center">
        <div class="p-3 rounded-full bg-blue-100 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400">
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"/></svg>
        </div>
        <div class="ml-4">
          <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Total Leads</p>
          <p class="text-2xl font-bold text-gray-900 dark:text-white">{{ stats().totalLeads }}</p>
        </div>
      </div>
    </div>
    @if (user()?.role === 'admin') {
      <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
        <div class="flex items-center">
          <div class="p-3 rounded-full bg-blue-100 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400">
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"/></svg>
          </div>
          <div class="ml-4">
            <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Employee Members</p>
            <p class="text-2xl font-bold text-gray-900 dark:text-white">{{ stats().totalUsers }}</p>
          </div>
        </div>
      </div>
    }
    <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
      <div class="flex items-center">
        <div class="p-3 rounded-full bg-yellow-100 dark:bg-yellow-900/20 text-yellow-600 dark:text-yellow-400">
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div class="ml-4">
          <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Pending Calls</p>
          <p class="text-2xl font-bold text-gray-900 dark:text-white">{{ stats().pendingCalls }}</p>
        </div>
      </div>
    </div>
    <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
      <div class="flex items-center">
        <div class="p-3 rounded-full bg-green-100 dark:bg-green-900/20 text-green-600 dark:text-green-400">
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg>
        </div>
        <div class="ml-4">
          <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Completed</p>
          <p class="text-2xl font-bold text-gray-900 dark:text-white">{{ stats().completedCalls }}</p>
        </div>
      </div>
    </div>
  </div>

  @if (showLeadsModal()) {
    <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div class="bg-white dark:bg-gray-800 rounded-lg w-full max-w-2xl shadow-lg">
        <div class="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
          <div>
            <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Total Leads Breakdown</h3>
            <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">{{ stats().totalLeads }} leads organized by source</p>
          </div>
          <button type="button" (click)="showLeadsModal.set(false)" class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300">
            <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
          </button>
        </div>
        <div class="p-6">
          <div class="space-y-3">
            @for (source of sourceKeys(); track source) {
              <div class="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700 rounded-lg border border-gray-200 dark:border-gray-600">
                <div class="flex items-center flex-1">
                  <svg class="h-5 w-5 text-gray-600 dark:text-gray-400 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
                  <div class="flex-1">
                    <h4 class="text-sm font-medium text-gray-900 dark:text-white">{{ source }}</h4>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{{ pctForSource(source) }}% of total</p>
                  </div>
                </div>
                <span class="text-lg font-bold text-gray-900 dark:text-white ml-4">{{ leadsGroupedBySource()[source].length }}</span>
              </div>
            }
            @if (sourceKeys().length === 0) {
              <div class="text-center py-8 text-gray-500 dark:text-gray-400">No leads found</div>
            }
          </div>
        </div>
        <div class="flex items-center justify-between p-6 border-t border-gray-200 dark:border-gray-700">
          <p class="text-sm text-gray-600 dark:text-gray-400">
            Total: {{ stats().totalLeads }} leads from {{ sourceKeys().length }} source{{ sourceKeys().length !== 1 ? 's' : '' }}
          </p>
          <button type="button" (click)="showLeadsModal.set(false)" class="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700">Close</button>
        </div>
      </div>
    </div>
  }

  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
    <div class="border-b border-gray-200 dark:border-gray-700">
      <nav class="flex space-x-8 px-6 overflow-x-auto scrollbar-hide">
        @if (user()?.role === 'admin') {
          <button type="button" (click)="activeTab.set('unassigned')"
            class="py-4 px-1 border-b-2 font-medium text-sm relative whitespace-nowrap"
            [class.border-primary-500]="activeTab()==='unassigned'"
            [class.text-primary-600]="activeTab()==='unassigned'"
            [class.dark:text-primary-400]="activeTab()==='unassigned'"
            [class.border-transparent]="activeTab()!=='unassigned'"
            [class.text-gray-500]="activeTab()!=='unassigned'"
            [class.dark:text-gray-400]="activeTab()!=='unassigned'">
            <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
            Unassigned Leads
            @if (stats().unassignedLeads > 0) {
              <span class="ml-2 px-2 py-0.5 text-xs font-bold bg-orange-500 text-white rounded-full">{{ stats().unassignedLeads }}</span>
            }
          </button>
        }
        <button type="button" (click)="activeTab.set('clients')" class="py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap"
          [class.border-primary-500]="activeTab()==='clients'" [class.text-primary-600]="activeTab()==='clients'" [class.dark:text-primary-400]="activeTab()==='clients'"
          [class.border-transparent]="activeTab()!=='clients'" [class.text-gray-500]="activeTab()!=='clients'"
          [class.dark:text-gray-400]="activeTab()!=='clients'">
          <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"/></svg>
          Leads
        </button>
        @if (user()?.role !== 'admin') {
          <button type="button" (click)="activeTab.set('history')" class="py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap"
            [class.border-primary-500]="activeTab()==='history'" [class.text-primary-600]="activeTab()==='history'" [class.dark:text-primary-400]="activeTab()==='history'"
            [class.border-transparent]="activeTab()!=='history'" [class.text-gray-500]="activeTab()!=='history'">
            <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            Call History
          </button>
        }
        <button type="button" (click)="activeTab.set('statistics')" class="py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap"
          [class.border-primary-500]="activeTab()==='statistics'" [class.text-primary-600]="activeTab()==='statistics'" [class.dark:text-primary-400]="activeTab()==='statistics'"
          [class.border-transparent]="activeTab()!=='statistics'" [class.text-gray-500]="activeTab()!=='statistics'">
          <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"/></svg>
          Statistics
        </button>
        @if (user()?.role === 'admin') {
          <button type="button" (click)="activeTab.set('users')" class="py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap"
            [class.border-primary-500]="activeTab()==='users'" [class.text-primary-600]="activeTab()==='users'" [class.dark:text-primary-400]="activeTab()==='users'"
            [class.border-transparent]="activeTab()!=='users'" [class.text-gray-500]="activeTab()!=='users'">
            <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"/></svg>
            Employee Management
          </button>
          <button type="button" (click)="activeTab.set('mapping')" class="py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap"
            [class.border-primary-500]="activeTab()==='mapping'" [class.text-primary-600]="activeTab()==='mapping'" [class.dark:text-primary-400]="activeTab()==='mapping'"
            [class.border-transparent]="activeTab()!=='mapping'" [class.text-gray-500]="activeTab()!=='mapping'">
            <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"/></svg>
            Mapping Management
          </button>
          <button type="button" (click)="activeTab.set('brandpartner')" class="py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap"
            [class.border-primary-500]="activeTab()==='brandpartner'" [class.text-primary-600]="activeTab()==='brandpartner'" [class.dark:text-primary-400]="activeTab()==='brandpartner'"
            [class.border-transparent]="activeTab()!=='brandpartner'" [class.text-gray-500]="activeTab()!=='brandpartner'">
            <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"/></svg>
            Brand Partner Management
          </button>
          <button type="button" (click)="activeTab.set('reports')" class="py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap"
            [class.border-primary-500]="activeTab()==='reports'" [class.text-primary-600]="activeTab()==='reports'" [class.dark:text-primary-400]="activeTab()==='reports'"
            [class.border-transparent]="activeTab()!=='reports'" [class.text-gray-500]="activeTab()!=='reports'">
            <svg class="h-4 w-4 inline mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>
            Reports
          </button>
        }
      </nav>
    </div>
    <div class="p-3">
      @if (activeTab()==='unassigned' && user()?.role === 'admin') {
        <app-unassigned-leads (statsChanged)="fetchStats()" />
      }
      @if (activeTab()==='clients') {
        <app-client-management (statsChanged)="fetchStats()" (goUnassigned)="activeTab.set('unassigned')" />
      }
      @if (activeTab()==='history' && user()?.role !== 'admin') {
        <app-call-history />
      }
      @if (activeTab()==='statistics') {
        <app-statistics />
      }
      @if (activeTab()==='users' && user()?.role === 'admin') {
        <app-user-management (statsChanged)="fetchStats()" />
      }
      @if (activeTab()==='mapping' && user()?.role === 'admin') {
        <app-mapping-management />
      }
      @if (activeTab()==='brandpartner' && user()?.role === 'admin') {
        <app-brand-partner-management />
      }
      @if (activeTab()==='reports' && user()?.role === 'admin') {
        <app-reports />
      }
    </div>
  </div>
</div>
