// client/src/components/Statistics.jsx
import React, { useState, useEffect } from 'react'
import { BarChart3, TrendingUp, Users, Calendar, Filter, Clock, PhoneOff, ThumbsDown, CheckCircle, PhoneMissed, Power, Pause, XCircle, CalendarCheck, Ban, PhoneForwarded, CheckCheck, X } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import axios from 'axios'

const Statistics = () => {
  const { user } = useAuth()
  const [clients, setClients] = useState([])
  const [users, setUsers] = useState([])
  const [projectSources, setProjectSources] = useState([])
  const [filterType, setFilterType] = useState('all') // all, employee, dateRange, source
  const [selectedEmployee, setSelectedEmployee] = useState('')
  const [selectedSource, setSelectedSource] = useState('')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchData()
  }, [])

  const fetchData = async () => {
    try {
      setLoading(true)
      const [clientsRes, usersRes, sourcesRes] = await Promise.all([
        axios.get('/api/clients'),
        user.role === 'admin' ? axios.get('/api/users') : Promise.resolve({ data: [] }),
        axios.get('/api/project-sources')
      ])
      
      setClients(clientsRes.data)
      setUsers(usersRes.data.filter(u => (u.role === 'sales' || u.role === 'mapping') && u.isActive))
      setProjectSources(sourcesRes.data)
    } catch (error) {
      console.error('Error fetching data:', error)
    } finally {
      setLoading(false)
    }
  }

  // Filter clients based on selected filters
  const getFilteredClients = () => {
    let filtered = [...clients]

    // For employees, always filter to show only their own leads
    if (user.role !== 'admin') {
      filtered = filtered.filter(c => c.assignedTo._id === user.id)
    }

    // Filter by employee (admin only)
    if (filterType === 'employee' && selectedEmployee) {
      filtered = filtered.filter(c => c.assignedTo._id === selectedEmployee)
    }

    // Filter by source
    if (filterType === 'source' && selectedSource) {
      filtered = filtered.filter(c => c.source === selectedSource)
    }

    // Always apply date range filter if dates are provided
    if (dateFrom || dateTo) {
      filtered = filtered.filter(c => {
        const createdDate = new Date(c.createdAt)
        
        // If both dates provided
        if (dateFrom && dateTo) {
          const fromDate = new Date(dateFrom)
          const toDate = new Date(dateTo)
          toDate.setHours(23, 59, 59, 999) // Include the entire end date
          return createdDate >= fromDate && createdDate <= toDate
        }
        
        // If only from date provided
        if (dateFrom && !dateTo) {
          const fromDate = new Date(dateFrom)
          return createdDate >= fromDate
        }
        
        // If only to date provided
        if (!dateFrom && dateTo) {
          const toDate = new Date(dateTo)
          toDate.setHours(23, 59, 59, 999)
          return createdDate <= toDate
        }
        
        return true
      })
    }

    return filtered
  }

  const filteredClients = getFilteredClients()

  // Get sources from project sources (only active/existing sources)
  const activeSources = projectSources.map(s => s.name).sort((a, b) => a.localeCompare(b))

  // Calculate statistics for each status
  const statusStats = [
    {
      key: 'pending',
      label: 'Pending',
      color: 'bg-amber-400 dark:bg-amber-500',
      bgLight: 'bg-amber-50 dark:bg-amber-900/20',
      textColor: 'text-amber-700 dark:text-amber-400',
      borderColor: 'border-amber-200 dark:border-amber-800',
      icon: Clock
    },
    {
      key: 'no-response',
      label: 'No Response',
      color: 'bg-slate-400 dark:bg-slate-500',
      bgLight: 'bg-slate-50 dark:bg-slate-900/20',
      textColor: 'text-slate-700 dark:text-slate-400',
      borderColor: 'border-slate-200 dark:border-slate-700',
      icon: PhoneOff
    },
    {
      key: 'not-interested',
      label: 'Not Interested',
      color: 'bg-rose-400 dark:bg-rose-500',
      bgLight: 'bg-rose-50 dark:bg-rose-900/20',
      textColor: 'text-rose-700 dark:text-rose-400',
      borderColor: 'border-rose-200 dark:border-rose-800',
      icon: ThumbsDown
    },
    {
      key: 'qualified',
      label: 'Qualified',
      color: 'bg-emerald-400 dark:bg-emerald-500',
      bgLight: 'bg-emerald-50 dark:bg-emerald-900/20',
      textColor: 'text-emerald-700 dark:text-emerald-400',
      borderColor: 'border-emerald-200 dark:border-emerald-800',
      icon: CheckCircle
    },
    {
      key: 'number-inactive',
      label: 'Number Inactive',
      color: 'bg-orange-400 dark:bg-orange-500',
      bgLight: 'bg-orange-50 dark:bg-orange-900/20',
      textColor: 'text-orange-700 dark:text-orange-400',
      borderColor: 'border-orange-200 dark:border-orange-800',
      icon: PhoneMissed
    },
    {
      key: 'number-switched-off',
      label: 'Number Switched Off',
      color: 'bg-pink-400 dark:bg-pink-500',
      bgLight: 'bg-pink-50 dark:bg-pink-900/20',
      textColor: 'text-pink-700 dark:text-pink-400',
      borderColor: 'border-pink-200 dark:border-pink-800',
      icon: Power
    },
    {
      key: 'on-hold',
      label: 'On Hold',
      color: 'bg-sky-400 dark:bg-sky-500',
      bgLight: 'bg-sky-50 dark:bg-sky-900/20',
      textColor: 'text-sky-700 dark:text-sky-400',
      borderColor: 'border-sky-200 dark:border-sky-800',
      icon: Pause
    },
    {
      key: 'no-requirement',
      label: 'No Requirement',
      color: 'bg-gray-400 dark:bg-gray-500',
      bgLight: 'bg-gray-50 dark:bg-gray-900/20',
      textColor: 'text-gray-700 dark:text-gray-400',
      borderColor: 'border-gray-200 dark:border-gray-700',
      icon: XCircle
    },
    {
      key: 'follow-up',
      label: 'Follow Up',
      color: 'bg-indigo-400 dark:bg-indigo-500',
      bgLight: 'bg-indigo-50 dark:bg-indigo-900/20',
      textColor: 'text-indigo-700 dark:text-indigo-400',
      borderColor: 'border-indigo-200 dark:border-indigo-800',
      icon: CalendarCheck
    },
    {
      key: 'disqualified',
      label: 'Disqualified',
      color: 'bg-red-400 dark:bg-red-500',
      bgLight: 'bg-red-50 dark:bg-red-900/20',
      textColor: 'text-red-700 dark:text-red-400',
      borderColor: 'border-red-200 dark:border-red-800',
      icon: Ban
    },
    {
      key: 'disconnected',
      label: 'Disconnected',
      color: 'bg-fuchsia-400 dark:bg-fuchsia-500',
      bgLight: 'bg-fuchsia-50 dark:bg-fuchsia-900/20',
      textColor: 'text-fuchsia-700 dark:text-fuchsia-400',
      borderColor: 'border-fuchsia-200 dark:border-fuchsia-800',
      icon: PhoneForwarded
    },
    {
      key: 'already-finalised',
      label: 'Already Finalised',
      color: 'bg-teal-400 dark:bg-teal-500',
      bgLight: 'bg-teal-50 dark:bg-teal-900/20',
      textColor: 'text-teal-700 dark:text-teal-400',
      borderColor: 'border-teal-200 dark:border-teal-800',
      icon: CheckCheck
    }
  ]

  const getStatusCount = (statusKey) => {
    return filteredClients.filter(c => c.status === statusKey).length
  }

  const totalLeads = filteredClients.length
  const getPercentage = (count) => {
    return totalLeads > 0 ? ((count / totalLeads) * 100).toFixed(1) : 0
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-500 dark:text-gray-400">Loading statistics...</div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
            <BarChart3 className="h-7 w-7 mr-2 text-primary-600 dark:text-primary-400" />
            {user.role === 'admin' ? 'Lead Statistics' : 'My Statistics'}
          </h2>
          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
            {user.role === 'admin' 
              ? 'Overview of lead status distribution' 
              : 'Overview of your assigned leads status distribution'}
          </p>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center">
            <Filter className="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" />
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Filters</h3>
          </div>
          {(filterType !== 'all' || selectedEmployee || selectedSource || dateFrom || dateTo) && (
            <button
              onClick={() => {
                setFilterType('all')
                setSelectedEmployee('')
                setSelectedSource('')
                setDateFrom('')
                setDateTo('')
              }}
              className="flex items-center px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
            >
              <X className="h-4 w-4 mr-1" />
              Clear Filters
            </button>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Filter Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Filter By
            </label>
            <select
              value={filterType}
              onChange={(e) => {
                setFilterType(e.target.value)
                setSelectedEmployee('')
                setSelectedSource('')
              }}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            >
              <option value="all">All Leads</option>
              {user.role === 'admin' && <option value="employee">By Employee</option>}
              <option value="source">By Source</option>
            </select>
          </div>

          {/* Employee Filter */}
          {filterType === 'employee' && user.role === 'admin' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Select Employee
              </label>
              <select
                value={selectedEmployee}
                onChange={(e) => setSelectedEmployee(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              >
                <option value="">All Employees</option>
                {users.map(u => (
                  <option key={u._id} value={u._id}>{u.name}</option>
                ))}
              </select>
            </div>
          )}

          {/* Source Filter */}
          {filterType === 'source' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Select Source
              </label>
              <select
                value={selectedSource}
                onChange={(e) => setSelectedSource(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              >
                <option value="">All Sources</option>
                {activeSources.map(source => (
                  <option key={source} value={source}>{source}</option>
                ))}
              </select>
            </div>
          )}

          {/* From Date - Always visible */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              From Date
            </label>
            <input
              type="date"
              value={dateFrom}
              onChange={(e) => setDateFrom(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            />
          </div>

          {/* To Date - Always visible */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              To Date
            </label>
            <input
              type="date"
              value={dateTo}
              onChange={(e) => setDateTo(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            />
          </div>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Total Leads</p>
              <p className="text-3xl font-bold text-gray-900 dark:text-white mt-2">{totalLeads}</p>
            </div>
            <div className="p-3 bg-blue-100 dark:bg-blue-900/20 rounded-full">
              <Users className="h-6 w-6 text-blue-600 dark:text-blue-400" />
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Qualified</p>
              <p className="text-3xl font-bold text-green-600 dark:text-green-400 mt-2">
                {getStatusCount('qualified')}
              </p>
            </div>
            <div className="p-3 bg-green-100 dark:bg-green-900/20 rounded-full">
              <TrendingUp className="h-6 w-6 text-green-600 dark:text-green-400" />
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Pending</p>
              <p className="text-3xl font-bold text-yellow-600 dark:text-yellow-400 mt-2">
                {getStatusCount('pending')}
              </p>
            </div>
            <div className="p-3 bg-yellow-100 dark:bg-yellow-900/20 rounded-full">
              <Calendar className="h-6 w-6 text-yellow-600 dark:text-yellow-400" />
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Follow Up</p>
              <p className="text-3xl font-bold text-purple-600 dark:text-purple-400 mt-2">
                {getStatusCount('follow-up')}
              </p>
            </div>
            <div className="p-3 bg-purple-100 dark:bg-purple-900/20 rounded-full">
              <BarChart3 className="h-6 w-6 text-purple-600 dark:text-purple-400" />
            </div>
          </div>
        </div>
      </div>

      {/* Status Cards Grid */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">
          Lead Status Breakdown
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          {statusStats.map(status => {
            const count = getStatusCount(status.key)
            const percentage = getPercentage(count)
            const IconComponent = status.icon
            
            return (
              <div
                key={status.key}
                className={`${status.bgLight} rounded-lg p-4 border ${status.borderColor}`}
              >
                <div className="flex items-center justify-between mb-2">
                  <div className={`p-2 rounded-lg ${status.bgLight}`}>
                    <IconComponent className={`h-6 w-6 ${status.textColor}`} />
                  </div>
                  <span className={`text-2xl font-bold ${status.textColor}`}>
                    {count}
                  </span>
                </div>
                <h4 className="text-sm font-semibold text-gray-900 dark:text-white mb-1">
                  {status.label}
                </h4>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-gray-600 dark:text-gray-400">
                    {percentage}% of total
                  </span>
                </div>
                {/* Progress bar */}
                <div className="mt-2 w-full bg-gray-200 dark:bg-gray-700 rounded-full h-1.5">
                  <div
                    className={`${status.color} h-1.5 rounded-full transition-all duration-300`}
                    style={{ width: `${percentage}%` }}
                  />
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Additional Info */}
      {(user.role !== 'admin' || filterType !== 'all' || (dateFrom && dateTo)) && (
        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
          <p className="text-sm text-blue-800 dark:text-blue-200">
            <strong>Note:</strong> 
            {user.role !== 'admin' && ' Showing statistics for your assigned leads only.'}
            {user.role === 'admin' && ' Statistics are filtered based on your selection.'}
            {filterType === 'employee' && selectedEmployee && ` Showing data for ${users.find(u => u._id === selectedEmployee)?.name}.`}
            {filterType === 'source' && selectedSource && ` Showing data for source: ${selectedSource}.`}
            {dateFrom && dateTo && ` Date range: ${dateFrom} to ${dateTo}.`}
            {dateFrom && !dateTo && ` Showing data from ${dateFrom} onwards.`}
            {!dateFrom && dateTo && ` Showing data up to ${dateTo}.`}
          </p>
        </div>
      )}
    </div>
  )
}

export default Statistics

// client-new/src/app/features/statistics/statistics.component.ts
import { Component, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth.service';
import { Client, EmployeeUser, ProjectSource } from '../../models';

type StatisticsStatusIcon =
  | 'clock'
  | 'phone-slash'
  | 'thumb-down'
  | 'check-circle'
  | 'phone-x'
  | 'power'
  | 'pause'
  | 'x-circle'
  | 'calendar'
  | 'prohibition'
  | 'phone-missed'
  | 'check-double';

@Component({
  selector: 'app-statistics',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './statistics.component.html',
})
export class StatisticsComponent {
  private readonly http = inject(HttpClient);
  private readonly auth = inject(AuthService);

  readonly clients = signal<Client[]>([]);
  readonly users = signal<EmployeeUser[]>([]);
  readonly projectSources = signal<ProjectSource[]>([]);
  readonly filterType = signal<'all' | 'employee' | 'source'>('all');
  readonly selectedEmployee = signal('');
  readonly selectedSource = signal('');
  readonly dateFrom = signal('');
  readonly dateTo = signal('');
  readonly loading = signal(true);

  readonly user = computed(() => this.auth.user());

  constructor() {
    void this.fetchData();
  }

  async fetchData(): Promise<void> {
    const u = this.user();
    if (!u) return;
    this.loading.set(true);
    try {
      const [clientsRes, usersRes, sourcesRes] = await Promise.all([
        firstValueFrom(this.http.get<Client[]>('/api/clients')),
        u.role === 'admin' ? firstValueFrom(this.http.get<EmployeeUser[]>('/api/users')) : Promise.resolve([] as EmployeeUser[]),
        firstValueFrom(this.http.get<ProjectSource[]>('/api/project-sources')),
      ]);
      this.clients.set(clientsRes);
      this.users.set(usersRes.filter((x) => (x.role === 'sales' || x.role === 'mapping') && x.isActive));
      this.projectSources.set(sourcesRes);
    } catch (e) {
      console.error(e);
    } finally {
      this.loading.set(false);
    }
  }

  getFilteredClients(): Client[] {
    const u = this.user();
    if (!u) return [];
    let filtered = [...this.clients()];
    if (u.role !== 'admin') {
      filtered = filtered.filter((c) => c.assignedTo?._id === u.id);
    }
    if (this.filterType() === 'employee' && this.selectedEmployee()) {
      filtered = filtered.filter((c) => c.assignedTo?._id === this.selectedEmployee());
    }
    if (this.filterType() === 'source' && this.selectedSource()) {
      filtered = filtered.filter((c) => c.source === this.selectedSource());
    }
    const df = this.dateFrom();
    const dt = this.dateTo();
    if (df || dt) {
      filtered = filtered.filter((c) => {
        const createdDate = new Date(c.createdAt || 0);
        if (df && dt) {
          const fromDate = new Date(df);
          const toDate = new Date(dt);
          toDate.setHours(23, 59, 59, 999);
          return createdDate >= fromDate && createdDate <= toDate;
        }
        if (df && !dt) return createdDate >= new Date(df);
        if (!df && dt) {
          const toDate = new Date(dt);
          toDate.setHours(23, 59, 59, 999);
          return createdDate <= toDate;
        }
        return true;
      });
    }
    return filtered;
  }

  activeSources(): string[] {
    return this.projectSources()
      .map((s) => s.name)
      .sort((a, b) => a.localeCompare(b));
  }

  getStatusCount(key: string): number {
    return this.getFilteredClients().filter((c) => c.status === key).length;
  }

  totalLeads(): number {
    return this.getFilteredClients().length;
  }

  pct(count: number): string {
    const t = this.totalLeads();
    return t > 0 ? ((count / t) * 100).toFixed(1) : '0';
  }

  onFilterTypeChange(v: string): void {
    this.filterType.set(v as 'all' | 'employee' | 'source');
    this.selectedEmployee.set('');
    this.selectedSource.set('');
  }

  clearFilters(): void {
    this.filterType.set('all');
    this.selectedEmployee.set('');
    this.selectedSource.set('');
    this.dateFrom.set('');
    this.dateTo.set('');
  }

  showClear(): boolean {
    return (
      this.filterType() !== 'all' ||
      !!this.selectedEmployee() ||
      !!this.selectedSource() ||
      !!this.dateFrom() ||
      !!this.dateTo()
    );
  }

  selectedEmployeeName(): string {
    const id = this.selectedEmployee();
    if (!id) return '';
    return this.users().find((u) => u._id === id)?.name || '';
  }

  /** Order and styling aligned with Lead Statistics reference UI */
  readonly statusStats: Array<{
    key: string;
    label: string;
    icon: StatisticsStatusIcon;
    iconWrap: string;
    iconClass: string;
    cardClass: string;
    countClass: string;
    barClass: string;
    trackClass: string;
  }> = [
    {
      key: 'pending',
      label: 'Pending',
      icon: 'clock',
      iconWrap: 'bg-amber-500/15 ring-1 ring-amber-500/30',
      iconClass: 'text-amber-400',
      cardClass: 'border-amber-500/25 bg-slate-800/90 shadow-sm shadow-amber-900/10',
      countClass: 'text-amber-400',
      barClass: 'bg-amber-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'no-response',
      label: 'No Response',
      icon: 'phone-slash',
      iconWrap: 'bg-slate-500/15 ring-1 ring-slate-500/30',
      iconClass: 'text-slate-400',
      cardClass: 'border-slate-500/25 bg-slate-800/90',
      countClass: 'text-slate-300',
      barClass: 'bg-slate-400',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'not-interested',
      label: 'Not Interested',
      icon: 'thumb-down',
      iconWrap: 'bg-rose-500/15 ring-1 ring-rose-500/30',
      iconClass: 'text-rose-400',
      cardClass: 'border-rose-500/25 bg-slate-800/90 shadow-sm shadow-rose-900/10',
      countClass: 'text-rose-400',
      barClass: 'bg-rose-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'qualified',
      label: 'Qualified',
      icon: 'check-circle',
      iconWrap: 'bg-emerald-500/15 ring-1 ring-emerald-500/30',
      iconClass: 'text-emerald-400',
      cardClass: 'border-emerald-500/25 bg-slate-800/90',
      countClass: 'text-emerald-400',
      barClass: 'bg-emerald-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'number-inactive',
      label: 'Number Inactive',
      icon: 'phone-x',
      iconWrap: 'bg-orange-500/15 ring-1 ring-orange-500/30',
      iconClass: 'text-orange-400',
      cardClass: 'border-orange-500/25 bg-slate-800/90',
      countClass: 'text-orange-400',
      barClass: 'bg-orange-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'number-switched-off',
      label: 'Number Switched Off',
      icon: 'power',
      iconWrap: 'bg-pink-500/15 ring-1 ring-pink-500/30',
      iconClass: 'text-pink-400',
      cardClass: 'border-pink-500/25 bg-slate-800/90',
      countClass: 'text-pink-400',
      barClass: 'bg-pink-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'on-hold',
      label: 'On Hold',
      icon: 'pause',
      iconWrap: 'bg-sky-500/15 ring-1 ring-sky-500/30',
      iconClass: 'text-sky-400',
      cardClass: 'border-sky-500/25 bg-slate-800/90',
      countClass: 'text-sky-400',
      barClass: 'bg-sky-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'no-requirement',
      label: 'No Requirement',
      icon: 'x-circle',
      iconWrap: 'bg-gray-500/15 ring-1 ring-gray-500/30',
      iconClass: 'text-gray-400',
      cardClass: 'border-gray-500/25 bg-slate-800/90',
      countClass: 'text-gray-300',
      barClass: 'bg-gray-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'follow-up',
      label: 'Follow Up',
      icon: 'calendar',
      iconWrap: 'bg-blue-500/15 ring-1 ring-blue-500/30',
      iconClass: 'text-blue-400',
      cardClass: 'border-blue-500/25 bg-slate-800/90',
      countClass: 'text-blue-400',
      barClass: 'bg-blue-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'disqualified',
      label: 'Disqualified',
      icon: 'prohibition',
      iconWrap: 'bg-orange-600/15 ring-1 ring-orange-500/35',
      iconClass: 'text-orange-400',
      cardClass: 'border-orange-600/30 bg-slate-800/90',
      countClass: 'text-orange-400',
      barClass: 'bg-orange-600',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'disconnected',
      label: 'Disconnected',
      icon: 'phone-missed',
      iconWrap: 'bg-violet-500/15 ring-1 ring-violet-500/30',
      iconClass: 'text-violet-400',
      cardClass: 'border-violet-500/25 bg-slate-800/90',
      countClass: 'text-violet-400',
      barClass: 'bg-violet-500',
      trackClass: 'bg-slate-700/80',
    },
    {
      key: 'already-finalised',
      label: 'Already Finalised',
      icon: 'check-double',
      iconWrap: 'bg-teal-500/15 ring-1 ring-teal-500/30',
      iconClass: 'text-teal-400',
      cardClass: 'border-teal-500/25 bg-slate-800/90',
      countClass: 'text-teal-400',
      barClass: 'bg-teal-500',
      trackClass: 'bg-slate-700/80',
    },
  ];
}

@if (loading()) {
  <div class="flex items-center justify-center h-64">
    <div class="text-gray-500 dark:text-gray-400">Loading statistics...</div>
  </div>
} @else {
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
          <svg class="h-7 w-7 mr-2 text-primary-600 dark:text-primary-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
          </svg>
          {{ user()?.role === 'admin' ? 'Lead Statistics' : 'My Statistics' }}
        </h2>
        <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">
          {{ user()?.role === 'admin' ? 'Overview of lead status distribution' : 'Overview of your assigned leads status distribution' }}
        </p>
      </div>
    </div>

    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
      <div class="flex items-center justify-between mb-4">
        <div class="flex items-center">
          <svg class="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" />
          </svg>
          <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Filters</h3>
        </div>
        @if (showClear()) {
          <button
            type="button"
            (click)="clearFilters()"
            class="flex items-center px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
          >
            <svg class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
            Clear Filters
          </button>
        }
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Filter By</label>
          <select
            [value]="filterType()"
            (change)="onFilterTypeChange($any($event.target).value)"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
          >
            <option value="all">All Leads</option>
            @if (user()?.role === 'admin') {
              <option value="employee">By Employee</option>
            }
            <option value="source">By Source</option>
          </select>
        </div>

        @if (filterType() === 'employee' && user()?.role === 'admin') {
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Select Employee</label>
            <select
              [ngModel]="selectedEmployee()"
              (ngModelChange)="selectedEmployee.set($event)"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            >
              <option value="">All Employees</option>
              @for (u of users(); track u._id) {
                <option [value]="u._id">{{ u.name }}</option>
              }
            </select>
          </div>
        }

        @if (filterType() === 'source') {
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Select Source</label>
            <select
              [ngModel]="selectedSource()"
              (ngModelChange)="selectedSource.set($event)"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            >
              <option value="">All Sources</option>
              @for (s of activeSources(); track s) {
                <option [value]="s">{{ s }}</option>
              }
            </select>
          </div>
        }

        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">From Date</label>
          <input
            type="date"
            [ngModel]="dateFrom()"
            (ngModelChange)="dateFrom.set($event)"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">To Date</label>
          <input
            type="date"
            [ngModel]="dateTo()"
            (ngModelChange)="dateTo.set($event)"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
          />
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
      <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Total Leads</p>
            <p class="text-3xl font-bold text-gray-900 dark:text-white mt-2">{{ totalLeads() }}</p>
          </div>
          <div class="p-3 bg-blue-100 dark:bg-blue-900/20 rounded-full">
            <svg class="h-6 w-6 text-blue-600 dark:text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
          </div>
        </div>
      </div>

      <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Qualified</p>
            <p class="text-3xl font-bold text-green-600 dark:text-green-400 mt-2">{{ getStatusCount('qualified') }}</p>
          </div>
          <div class="p-3 bg-green-100 dark:bg-green-900/20 rounded-full">
            <svg class="h-6 w-6 text-green-600 dark:text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
            </svg>
          </div>
        </div>
      </div>

      <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Pending</p>
            <p class="text-3xl font-bold text-yellow-600 dark:text-yellow-400 mt-2">{{ getStatusCount('pending') }}</p>
          </div>
          <div class="p-3 bg-yellow-100 dark:bg-yellow-900/20 rounded-full">
            <svg class="h-6 w-6 text-yellow-600 dark:text-yellow-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>
        </div>
      </div>

      <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600 dark:text-gray-400">Follow Up</p>
            <p class="text-3xl font-bold text-purple-600 dark:text-purple-400 mt-2">{{ getStatusCount('follow-up') }}</p>
          </div>
          <div class="p-3 bg-purple-100 dark:bg-purple-900/20 rounded-full">
            <svg class="h-6 w-6 text-purple-600 dark:text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-6">Lead Status Breakdown</h3>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        @for (status of statusStats; track status.key) {
          @let count = getStatusCount(status.key);
          @let percentage = pct(count);
          <div class="{{ status.cardClass }} rounded-lg p-4 border">
            <div class="flex items-center justify-between mb-2">
              <div class="p-2 rounded-lg {{ status.iconWrap }}">
                <svg class="h-6 w-6 {{ status.iconClass }}" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  @switch (status.icon) {
                    @case ('clock') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    }
                    @case ('phone-slash') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 20L20 4" />
                    }
                    @case ('thumb-down') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M7.5 3.75v11.5a1.5 1.5 0 001.356 1.491l.144.009h2.25a1.5 1.5 0 001.491-1.356l.009-.144V12h2.13l2.622 6.554A2.25 2.25 0 0018.75 20.25h.75a1.5 1.5 0 001.5-1.5v-2.625a2.625 2.625 0 00-2.625-2.625H16.5v-1.5a2.25 2.25 0 00-2.25-2.25h-1.5a2.25 2.25 0 01-2.25-2.25V6a2.25 2.25 0 012.25-2.25H16.5V3.75a1.5 1.5 0 00-1.5-1.5h-7.5z" />
                    }
                    @case ('check-circle') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    }
                    @case ('phone-x') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16 9l6 6m0-6l-6 6" />
                    }
                    @case ('power') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M5.636 5.636a9 9 0 1012.728 12.728M12 3v9" />
                    }
                    @case ('pause') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 5h3v14H6V5zm9 0h3v14h-3V5z" />
                    }
                    @case ('x-circle') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    }
                    @case ('calendar') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    }
                    @case ('prohibition') {
                      <circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="1.5" />
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M7 17L17 7" />
                    }
                    @case ('phone-missed') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 4h6M18 4v7M15 8l6-4" />
                    }
                    @case ('check-double') {
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.5 12.5l2.5 2.5 5.5-5.5" />
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 10.5l2.5 2.5 6.5-6.5" />
                    }
                  }
                </svg>
              </div>
              <span class="text-2xl font-bold {{ status.countClass }}">{{ count }}</span>
            </div>
            <h4 class="text-sm font-semibold text-gray-900 dark:text-white mb-1">{{ status.label }}</h4>
            <div class="flex items-center justify-between">
              <span class="text-xs text-gray-600 dark:text-gray-400">{{ percentage }}% of total</span>
            </div>
            <div class="mt-2 w-full bg-gray-200 dark:bg-gray-700 rounded-full h-1.5 {{ status.trackClass }}">
              <div class="{{ status.barClass }} h-1.5 rounded-full transition-all duration-300" [style.width]="percentage + '%'"></div>
            </div>
          </div>
        }
      </div>
    </div>

    @if (user()?.role !== 'admin' || filterType() !== 'all' || (dateFrom() && dateTo())) {
      <div class="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
        <p class="text-sm text-blue-800 dark:text-blue-200">
          <strong>Note:</strong>
          @if (user()?.role !== 'admin') {
            <span> Showing statistics for your assigned leads only.</span>
          }
          @if (user()?.role === 'admin') {
            <span> Statistics are filtered based on your selection.</span>
          }
          @if (filterType() === 'employee' && selectedEmployee()) {
            <span> Showing data for {{ selectedEmployeeName() }}.</span>
          }
          @if (filterType() === 'source' && selectedSource()) {
            <span> Showing data for source: {{ selectedSource() }}.</span>
          }
          @if (dateFrom() && dateTo()) {
            <span> Date range: {{ dateFrom() }} to {{ dateTo() }}.</span>
          }
          @if (dateFrom() && !dateTo()) {
            <span> Showing data from {{ dateFrom() }} onwards.</span>
          }
          @if (!dateFrom() && dateTo()) {
            <span> Showing data up to {{ dateTo() }}.</span>
          }
        </p>
      </div>
    }
  </div>
}
