// brandpartnerdash/src/routes/partner-profile.tsx
import { createFileRoute, redirect } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { isAuthenticated } from "@/lib/auth";
import { useAuth, API_BASE } from "@/lib/auth";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import {
  Building2,
  Mail,
  Phone,
  CheckCircle2,
  CreditCard,
  Pencil,
  Check,
  X,
} from "lucide-react";

export const Route = createFileRoute("/partner-profile")({
  beforeLoad: () => {
    if (!isAuthenticated()) throw redirect({ to: "/login" });
  },
  head: () => ({
    meta: [
      { title: "Partner Profile — Brand Partner" },
      { name: "description", content: "Your partner profile." },
    ],
  }),
  component: PartnerProfilePage,
});

type FullProfile = {
  _id: string;
  partnerName: string;
  nickName: string;
  contactPerson1: string;
  phoneNo1: string;
  contactPerson2?: string;
  phoneNo2?: string;
  email: string;
  address: string;
  about?: string;
  accountHolderName: string;
  accountNumber: string;
  bankName: string;
  ifscCode: string;
  pan: string;
  partnerCode: string;
  paymentTerms?: string;
  remarks?: string;
  isActive: boolean;
  createdAt: string;
  memberSince?: string;
};

function initials(name?: string) {
  if (!name) return "BP";
  return name.split(" ").map((w) => w[0]).join("").slice(0, 2).toUpperCase();
}

function PartnerProfilePage() {
  const { token } = useAuth();
  const [profile, setProfile] = useState<FullProfile | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!error) return;
    const id = setTimeout(() => setError(null), 4000);
    return () => clearTimeout(id);
  }, [error]);
  const [editingAbout, setEditingAbout] = useState(false);
  const [aboutDraft, setAboutDraft] = useState("");
  const [savingAbout, setSavingAbout] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (!token) return;
    fetch(`${API_BASE}/api/brand-partners/profile`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((r) => {
        if (!r.ok) throw new Error("Failed to load profile");
        return r.json() as Promise<FullProfile>;
      })
      .then(setProfile)
      .catch((e: Error) => setError(e.message));
  }, [token]);

  const p = profile;

  async function saveAbout() {
    if (!token || !p) return;
    setSavingAbout(true);
    try {
      const res = await fetch(`${API_BASE}/api/brand-partners/profile/about`, {
        method: "PUT",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ about: aboutDraft }),
      });
      if (!res.ok) throw new Error("Failed to save");
      setProfile({ ...p, about: aboutDraft });
      setEditingAbout(false);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to save");
    } finally {
      setSavingAbout(false);
    }
  }

  return (
    <AppShell>
      <div className="flex flex-1 flex-col gap-6">
        {/* Hero */}
        <div
          className="relative overflow-hidden rounded-2xl p-8 text-white shadow-[var(--shadow-card)]"
          style={{ backgroundImage: "var(--gradient-hero)" }}
        >
          <div className="flex flex-wrap items-center gap-6">
            <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-white/15 text-3xl font-bold backdrop-blur">
              {p ? initials(p.partnerName) : <Skeleton className="h-10 w-10 rounded bg-white/20" />}
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-2">
                {p ? (
                  <>
                    <h1 className="text-2xl font-extrabold">{p.partnerName}</h1>
                    {p.nickName && (
                      <span className="rounded-full bg-white/20 px-2.5 py-0.5 text-sm font-medium text-white/90">
                        {p.nickName}
                      </span>
                    )}
                  </>
                ) : (
                  <Skeleton className="h-7 w-48 rounded bg-white/20" />
                )}
                {p?.isActive && <CheckCircle2 className="h-5 w-5 text-white" />}
              </div>
              <div className="mt-1 text-sm text-white/80">
                {p ? (
                  <>
                    {p.partnerCode}
                    {p.memberSince && (
                      <> · Member since {new Date(p.memberSince).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })}</>
                    )}
                  </>
                ) : <Skeleton className="mt-1 h-4 w-64 rounded bg-white/20" />}
              </div>
              {p && (
                <div className="mt-3 flex flex-wrap gap-2">
                  <Badge className="border-0 bg-white/20 text-white">Verified</Badge>
                  {p.isActive && <Badge className="border-0 bg-white/20 text-white">Active</Badge>}
                  {p.partnerCode && <Badge className="border-0 bg-white/20 text-white">{p.partnerCode}</Badge>}
                </div>
              )}
            </div>
          </div>
        </div>

        {error && (
          <div className="rounded-xl border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">
            {error}
          </div>
        )}

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <div className="space-y-6 lg:col-span-2">
            {/* About */}
            <section className="rounded-2xl border border-border bg-card p-6 shadow-[var(--shadow-card)]">
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold">About</h2>
                {p && !editingAbout && (
                  <Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => { setAboutDraft(p.about ?? ""); setEditingAbout(true); setTimeout(() => textareaRef.current?.focus(), 0); }}>
                    <Pencil className="h-4 w-4" />
                  </Button>
                )}
              </div>
              {editingAbout ? (
                <div className="mt-3 space-y-3">
                  <textarea
                    ref={textareaRef}
                    value={aboutDraft}
                    onChange={(e) => setAboutDraft(e.target.value)}
                    rows={4}
                    className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground outline-none focus:ring-2 focus:ring-primary resize-none"
                    placeholder="Write something about your business…"
                  />
                  <div className="flex justify-end gap-2">
                    <Button size="sm" variant="outline" onClick={() => setEditingAbout(false)}>
                      <X className="mr-1 h-3.5 w-3.5" /> Cancel
                    </Button>
                    <Button size="sm" onClick={saveAbout} disabled={savingAbout}>
                      <Check className="mr-1 h-3.5 w-3.5" /> {savingAbout ? "Saving…" : "Save"}
                    </Button>
                  </div>
                </div>
              ) : (
                <p className="mt-2 text-sm text-muted-foreground">
                  {p ? (p.about || "No description yet. Click the pencil icon to add one.") : <Skeleton className="h-4 w-full rounded" />}
                </p>
              )}
            </section>
            <section className="rounded-2xl border border-border bg-card p-6 shadow-[var(--shadow-card)]">
              <h2 className="text-lg font-semibold">Partner Details</h2>
              <dl className="mt-4 grid grid-cols-1 gap-4 text-sm sm:grid-cols-2">
                {([
                  ["Partner Name", p?.partnerName],
                  ["Nick Name", p?.nickName],
                  ["Contact Person 1", p?.contactPerson1],
                  ["Contact Person 2", p?.contactPerson2],
                  ["PAN", p?.pan],
                  ["Payment Terms", p?.paymentTerms],
                  ["Address", p?.address],
                ] as [string, string | undefined][]).map(([label, value]) => (
                  value !== undefined && value !== "" ? (
                    <div key={label} className={label === "Address" || label === "About" ? "sm:col-span-2" : ""}>
                      <dt className="text-xs font-medium text-muted-foreground">{label}</dt>
                      <dd className="mt-0.5 font-medium text-foreground">{value || "—"}</dd>
                    </div>
                  ) : !p ? (
                    <div key={label}>
                      <dt className="text-xs font-medium text-muted-foreground">{label}</dt>
                      <dd className="mt-0.5"><Skeleton className="h-4 w-32 rounded" /></dd>
                    </div>
                  ) : null
                ))}
              </dl>
            </section>

            {/* Bank Details */}
            <section className="rounded-2xl border border-border bg-card p-6 shadow-[var(--shadow-card)]">
              <h2 className="mb-4 text-lg font-semibold flex items-center gap-2">
                <CreditCard className="h-4 w-4 text-muted-foreground" /> Bank Details
              </h2>
              <dl className="grid grid-cols-1 gap-4 text-sm sm:grid-cols-2">
                {([
                  ["Bank Name", p?.bankName],
                  ["IFSC Code", p?.ifscCode],
                  ["Account Holder", p?.accountHolderName],
                  ["Account Number", p?.accountNumber ? `••••${p.accountNumber.slice(-4)}` : undefined],
                ] as [string, string | undefined][]).map(([label, value]) => (
                  <div key={label}>
                    <dt className="text-xs font-medium text-muted-foreground">{label}</dt>
                    <dd className="mt-0.5 font-medium text-foreground">
                      {value ?? <Skeleton className="h-4 w-32 rounded" />}
                    </dd>
                  </div>
                ))}
              </dl>
            </section>
          </div>

          {/* Contact */}
          <div className="space-y-6">
            <section className="rounded-2xl border border-border bg-card p-6 shadow-[var(--shadow-card)]">
              <h2 className="text-lg font-semibold">Contact</h2>
              <ul className="mt-3 space-y-3 text-sm">
                <li className="flex items-center gap-3">
                  <Mail className="h-4 w-4 shrink-0 text-muted-foreground" />
                  {p ? <span>{p.email}</span> : <Skeleton className="h-4 w-40 rounded" />}
                </li>
                <li className="flex items-center gap-3">
                  <Phone className="h-4 w-4 shrink-0 text-muted-foreground" />
                  {p ? <span>{p.contactPerson1} · {p.phoneNo1}</span> : <Skeleton className="h-4 w-32 rounded" />}
                </li>
                {p?.contactPerson2 && p.phoneNo2 && (
                  <li className="flex items-center gap-3">
                    <Phone className="h-4 w-4 shrink-0 text-muted-foreground" />
                    <span>{p.contactPerson2} · {p.phoneNo2}</span>
                  </li>
                )}
                <li className="flex items-start gap-3">
                  <Building2 className="h-4 w-4 shrink-0 text-muted-foreground mt-0.5" />
                  {p ? <span>{p.address}</span> : <Skeleton className="h-4 w-48 rounded" />}
                </li>
              </ul>
            </section>
          </div>
        </div>
      </div>
    </AppShell>
  );
}

// brandpartnerdash-angular/src/app/pages/partner-profile/partner-profile.component.ts
import { Component, ElementRef, OnInit, ViewChild, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth.service';
import { PartnerProfileIconComponent } from './partner-profile-icon.component';

type FullProfile = {
  _id: string;
  partnerName: string;
  nickName: string;
  contactPerson1: string;
  phoneNo1: string;
  contactPerson2?: string;
  phoneNo2?: string;
  email: string;
  address: string;
  about?: string;
  accountHolderName: string;
  accountNumber: string;
  bankName: string;
  ifscCode: string;
  pan: string;
  partnerCode: string;
  paymentTerms?: string;
  remarks?: string;
  isActive: boolean;
  createdAt: string;
  memberSince?: string;
};

@Component({
  selector: 'app-partner-profile',
  standalone: true,
  imports: [CommonModule, FormsModule, PartnerProfileIconComponent],
  templateUrl: './partner-profile.component.html',
  styles: [
    `
      :host {
        display: flex;
        flex: 1 1 auto;
        flex-direction: column;
        min-height: 0;
      }

      .profile-status-badge {
        transition:
          background-color 200ms ease,
          color 200ms ease,
          box-shadow 200ms ease,
          transform 200ms ease;
      }

      .profile-status-badge:hover {
        background: color-mix(in oklch, var(--primary) 82%, white);
        color: #fff;
        box-shadow: 0 0 0 1px color-mix(in oklch, var(--primary) 55%, transparent);
        transform: translateY(-1px);
      }

      .about-editing-field {
        caret-color: var(--primary);
      }
    `,
  ],
})
export class PartnerProfileComponent implements OnInit {
  private readonly http = inject(HttpClient);
  private readonly auth = inject(AuthService);

  @ViewChild('aboutInput') aboutInput?: ElementRef<HTMLTextAreaElement>;

  profile: FullProfile | null = null;
  error: string | null = null;
  editingAbout = false;
  aboutDraft = '';
  savingAbout = false;

  async ngOnInit(): Promise<void> {
    if (!this.auth.token()) return;
    try {
      this.profile = await firstValueFrom(this.http.get<FullProfile>('/api/brand-partners/profile'));
    } catch (error: unknown) {
      this.error = error instanceof Error ? error.message : 'Failed to load profile';
    }
  }

  initials(name?: string): string {
    if (!name) return 'BP';
    return name
      .split(' ')
      .map((word) => word[0])
      .join('')
      .slice(0, 2)
      .toUpperCase();
  }

  startEditAbout(): void {
    if (!this.profile) return;
    this.aboutDraft = this.profile.about ?? '';
    this.editingAbout = true;
    this.focusAboutInput();
  }

  cancelEditAbout(): void {
    this.editingAbout = false;
    this.aboutDraft = '';
  }

  async saveAbout(): Promise<void> {
    if (!this.profile) return;
    this.savingAbout = true;
    try {
      await firstValueFrom(
        this.http.put<FullProfile>('/api/brand-partners/profile/about', { about: this.aboutDraft }),
      );
      this.profile = { ...this.profile, about: this.aboutDraft };
      this.editingAbout = false;
    } catch (error: unknown) {
      this.error = error instanceof Error ? error.message : 'Failed to save';
    } finally {
      this.savingAbout = false;
    }
  }

  private focusAboutInput(): void {
    queueMicrotask(() => {
      const input = this.aboutInput?.nativeElement;
      if (!input) return;
      input.focus();
      const end = input.value.length;
      input.setSelectionRange(end, end);
    });
  }
}

<div class="flex min-h-0 flex-1 flex-col gap-6">
  <div class="relative overflow-hidden rounded-2xl p-8 text-white shadow-card" [style.background-image]="'var(--gradient-hero)'">
    <div class="flex flex-wrap items-center gap-6">
      <div class="flex h-20 w-20 shrink-0 items-center justify-center rounded-2xl bg-white/15 text-3xl font-bold backdrop-blur">
        {{ profile ? initials(profile.partnerName) : '…' }}
      </div>
      <div class="min-w-0 flex-1">
        <div class="flex flex-wrap items-center gap-2">
          @if (profile) {
            <h1 class="text-2xl font-extrabold tracking-tight">{{ profile.partnerName }}</h1>
            @if (profile.nickName) {
              <span class="rounded-full bg-white/20 px-2.5 py-0.5 text-sm font-medium text-white/90">{{ profile.nickName }}</span>
            }
            @if (profile.isActive) {
              <span class="inline-flex h-5 w-5 items-center justify-center text-white">
                <app-partner-profile-icon name="check-circle" />
              </span>
            }
          } @else {
            <div class="h-7 w-48 animate-pulse rounded bg-white/20"></div>
          }
        </div>
        <p class="mt-1 text-sm text-white/80">
          @if (profile) {
            {{ profile.partnerCode }}
            @if (profile.memberSince) {
              · Member since {{ profile.memberSince | date: 'MMM d, y' }}
            }
          }
        </p>
        @if (profile) {
          <div class="mt-3 flex flex-wrap gap-2">
            <span class="profile-status-badge rounded-full bg-white/20 px-2.5 py-0.5 text-xs font-medium text-white">Verified</span>
            @if (profile.isActive) {
              <span class="profile-status-badge rounded-full bg-white/20 px-2.5 py-0.5 text-xs font-medium text-white">Active</span>
            }
            @if (profile.partnerCode) {
              <span class="profile-status-badge rounded-full bg-white/20 px-2.5 py-0.5 text-xs font-medium text-white">{{ profile.partnerCode }}</span>
            }
          </div>
        }
      </div>
    </div>
  </div>

  @if (error) {
    <div class="rounded-xl border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{{ error }}</div>
  }

  <div class="grid grid-cols-1 items-start gap-6 lg:grid-cols-3">
    <div class="space-y-6 lg:col-span-2">
      <section class="rounded-2xl border border-border bg-card p-6 shadow-card">
        <div class="flex items-center justify-between gap-4">
          <h2 class="text-lg font-semibold">About</h2>
          @if (profile && !editingAbout) {
            <button
              type="button"
              class="inline-flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
              (click)="startEditAbout()"
              aria-label="Edit about"
            >
              <app-partner-profile-icon name="pencil" />
            </button>
          }
        </div>
        @if (editingAbout) {
          <div class="mt-3 space-y-3">
            <textarea
              #aboutInput
              [(ngModel)]="aboutDraft"
              rows="4"
              class="about-editing-field w-full resize-none rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary"
              placeholder="Write something about your business…"
            ></textarea>
            <div class="flex justify-end gap-2">
              <button type="button" class="inline-flex items-center gap-1 rounded-md border border-border px-3 py-1.5 text-sm" (click)="cancelEditAbout()">
                <app-partner-profile-icon name="x" />
                Cancel
              </button>
              <button type="button" class="inline-flex items-center gap-1 rounded-md bg-primary px-3 py-1.5 text-sm text-primary-foreground" [disabled]="savingAbout" (click)="saveAbout()">
                <app-partner-profile-icon name="check" />
                {{ savingAbout ? 'Saving…' : 'Save' }}
              </button>
            </div>
          </div>
        } @else {
          <p class="mt-2 text-sm text-muted-foreground">
            {{ profile?.about || 'No description yet. Click the pencil icon to add one.' }}
          </p>
        }
      </section>

      <section class="rounded-2xl border border-border bg-card p-6 shadow-card">
        <h2 class="text-lg font-semibold">Partner Details</h2>
        <dl class="mt-4 grid grid-cols-1 gap-4 text-sm sm:grid-cols-2">
          @if (profile) {
            <div>
              <dt class="text-xs font-medium text-muted-foreground">Partner Name</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.partnerName }}</dd>
            </div>
            <div>
              <dt class="text-xs font-medium text-muted-foreground">Nick Name</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.nickName || '—' }}</dd>
            </div>
            <div>
              <dt class="text-xs font-medium text-muted-foreground">Contact Person 1</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.contactPerson1 }}</dd>
            </div>
            @if (profile.contactPerson2) {
              <div>
                <dt class="text-xs font-medium text-muted-foreground">Contact Person 2</dt>
                <dd class="mt-0.5 font-medium text-foreground">{{ profile.contactPerson2 }}</dd>
              </div>
            }
            <div>
              <dt class="text-xs font-medium text-muted-foreground">PAN</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.pan }}</dd>
            </div>
            @if (profile.paymentTerms) {
              <div>
                <dt class="text-xs font-medium text-muted-foreground">Payment Terms</dt>
                <dd class="mt-0.5 font-medium text-foreground">{{ profile.paymentTerms }}</dd>
              </div>
            }
            <div class="sm:col-span-2">
              <dt class="text-xs font-medium text-muted-foreground">Address</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.address }}</dd>
            </div>
          }
        </dl>
      </section>

      <section class="rounded-2xl border border-border bg-card p-6 shadow-card">
        <h2 class="mb-4 flex items-center gap-2 text-lg font-semibold">
          <app-partner-profile-icon name="credit-card" class="text-muted-foreground" />
          Bank Details
        </h2>
        <dl class="grid grid-cols-1 gap-4 text-sm sm:grid-cols-2">
          @if (profile) {
            <div>
              <dt class="text-xs font-medium text-muted-foreground">Bank Name</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.bankName }}</dd>
            </div>
            <div>
              <dt class="text-xs font-medium text-muted-foreground">IFSC Code</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.ifscCode }}</dd>
            </div>
            <div>
              <dt class="text-xs font-medium text-muted-foreground">Account Holder</dt>
              <dd class="mt-0.5 font-medium text-foreground">{{ profile.accountHolderName }}</dd>
            </div>
            <div>
              <dt class="text-xs font-medium text-muted-foreground">Account Number</dt>
              <dd class="mt-0.5 font-medium text-foreground">••••{{ profile.accountNumber.slice(-4) }}</dd>
            </div>
          }
        </dl>
      </section>
    </div>

    <div class="space-y-6">
      <section class="rounded-2xl border border-border bg-card p-6 shadow-card">
        <h2 class="text-lg font-semibold">Contact</h2>
        <ul class="mt-3 space-y-3 text-sm">
          @if (profile) {
            <li class="flex items-center gap-3">
              <app-partner-profile-icon name="mail" class="text-muted-foreground" />
              <span class="text-foreground">{{ profile.email }}</span>
            </li>
            <li class="flex items-center gap-3">
              <app-partner-profile-icon name="phone" class="text-muted-foreground" />
              <span class="text-foreground">{{ profile.contactPerson1 }} · {{ profile.phoneNo1 }}</span>
            </li>
            @if (profile.contactPerson2 && profile.phoneNo2) {
              <li class="flex items-center gap-3">
                <app-partner-profile-icon name="phone" class="text-muted-foreground" />
                <span class="text-foreground">{{ profile.contactPerson2 }} · {{ profile.phoneNo2 }}</span>
              </li>
            }
            <li class="flex items-start gap-3">
              <app-partner-profile-icon name="building" class="mt-0.5 text-muted-foreground" />
              <span class="text-foreground">{{ profile.address }}</span>
            </li>
          }
        </ul>
      </section>
    </div>
  </div>
</div>
