// client-new/src/app/features/auto-assignment/auto-assignment-modal.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output,
  inject,
  signal,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { EmployeeUser, ProjectSource } from '../../models';

interface SourceAssignment {
  sourceName: string;
  assignedTo: string;
}

interface CsvFileAssignment {
  csvFileName: string;
  assignedTo: string;
}

interface AutoAssignmentSettings {
  excludedEmployees: { _id: string; name?: string }[];
  sourceAssignments?: { sourceName: string; assignedTo: string | { _id: string } }[];
  csvFileAssignments?: { csvFileName: string; assignedTo: string | { _id: string } }[];
}

@Component({
  selector: 'app-auto-assignment-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './auto-assignment-modal.component.html',
})
export class AutoAssignmentModalComponent implements OnChanges {
  private readonly http = inject(HttpClient);

  @Input() isOpen = false;
  @Input() users: EmployeeUser[] = [];
  @Input() projectSources: ProjectSource[] = [];
  @Output() closed = new EventEmitter<void>();
  /** Emitted after successful process-unassigned so parent can refresh stats */
  @Output() processed = new EventEmitter<void>();

  readonly loading = signal(false);
  readonly saving = signal(false);
  readonly excludedIds = signal<string[]>([]);
  readonly sourceAssignments = signal<SourceAssignment[]>([]);
  readonly csvFileAssignments = signal<CsvFileAssignment[]>([]);
  readonly csvFiles = signal<string[]>([]);
  readonly resultOpen = signal(false);
  readonly result = signal<{ type: 'success' | 'error'; title: string; message: string }>({
    type: 'success',
    title: '',
    message: '',
  });

  close(): void {
    this.resultOpen.set(false);
    this.closed.emit();
  }

  ngOnChanges(ch: SimpleChanges): void {
    if (ch['isOpen']?.currentValue === true) {
      void this.load();
    }
  }

  private resolveAssigneeId(v: string | { _id: string } | undefined): string {
    if (!v) return '';
    return typeof v === 'string' ? v : v._id;
  }

  async load(): Promise<void> {
    this.loading.set(true);
    try {
      const settings = await firstValueFrom(this.http.get<AutoAssignmentSettings>('/api/auto-assignment'));
      this.excludedIds.set((settings.excludedEmployees || []).map((e) => e._id));
      this.sourceAssignments.set(
        (settings.sourceAssignments || []).map((sa) => ({
          sourceName: sa.sourceName,
          assignedTo: this.resolveAssigneeId(sa.assignedTo),
        })),
      );
      this.csvFileAssignments.set(
        (settings.csvFileAssignments || []).map((ca) => ({
          csvFileName: ca.csvFileName,
          assignedTo: this.resolveAssigneeId(ca.assignedTo),
        })),
      );
      const files = await firstValueFrom(this.http.get<string[]>('/api/auto-assignment/csv-files'));
      this.csvFiles.set(Array.isArray(files) ? files : []);
    } catch (e) {
      console.error(e);
    } finally {
      this.loading.set(false);
    }
  }

  toggleExcluded(id: string): void {
    const cur = this.excludedIds();
    if (cur.includes(id)) this.excludedIds.set(cur.filter((x) => x !== id));
    else this.excludedIds.set([...cur, id]);
  }

  /** Same as legacy modal: sales/mapping + active only. */
  eligibleUsers(): EmployeeUser[] {
    return (this.users || []).filter((u) => (u.role === 'sales' || u.role === 'mapping') && u.isActive);
  }

  /** Subtitle under source name when API description is empty. */
  sourceSubtitle(s: ProjectSource): string {
    const d = (s.description || '').trim();
    if (d) return d;
    const defaults: Record<string, string> = {
      'CSV Imports': 'Automatically created for CSV imported leads',
      Mapping: 'Leads from Mapping source',
    };
    return defaults[s.name] || '';
  }

  isExcluded(id: string): boolean {
    return this.excludedIds().includes(id);
  }

  getSourceAssign(sourceName: string): string {
    return this.sourceAssignments().find((s) => s.sourceName === sourceName)?.assignedTo || '';
  }

  setSourceAssign(sourceName: string, employeeId: string): void {
    const prev = this.sourceAssignments().filter((s) => s.sourceName !== sourceName);
    if (employeeId) prev.push({ sourceName, assignedTo: employeeId });
    this.sourceAssignments.set(prev);
  }

  getCsvAssign(fileName: string): string {
    return this.csvFileAssignments().find((c) => c.csvFileName === fileName)?.assignedTo || '';
  }

  setCsvAssign(fileName: string, employeeId: string): void {
    const prev = this.csvFileAssignments().filter((c) => c.csvFileName !== fileName);
    if (employeeId) prev.push({ csvFileName: fileName, assignedTo: employeeId });
    this.csvFileAssignments.set(prev);
  }

  private payload() {
    return {
      excludedEmployees: this.excludedIds(),
      sourceAssignments: this.sourceAssignments(),
      csvFileAssignments: this.csvFileAssignments(),
    };
  }

  async save(): Promise<void> {
    this.saving.set(true);
    try {
      await firstValueFrom(this.http.put('/api/auto-assignment', this.payload()));
      this.result.set({ type: 'success', title: 'Settings Saved', message: 'Auto-assignment settings have been saved successfully.' });
      this.resultOpen.set(true);
    } catch (e: unknown) {
      const err = e as { error?: { message?: string } };
      this.result.set({
        type: 'error',
        title: 'Save Failed',
        message: err.error?.message || 'Failed to save settings.',
      });
      this.resultOpen.set(true);
    } finally {
      this.saving.set(false);
    }
  }

  async saveAndProcess(): Promise<void> {
    this.saving.set(true);
    try {
      await firstValueFrom(this.http.put('/api/auto-assignment', this.payload()));
      const res = await firstValueFrom(
        this.http.post<{ success: boolean; assignedCount?: number; failedCount?: number }>(
          '/api/auto-assignment/process-unassigned',
          {},
        ),
      );
      if (res.success) {
        const a = res.assignedCount ?? 0;
        const f = res.failedCount ?? 0;
        const message =
          f > 0 ? `Assigned ${a} lead(s). ${f} failed.` : `Successfully assigned ${a} lead(s).`;
        this.result.set({ type: 'success', title: 'Processing Complete', message });
        this.resultOpen.set(true);
        this.processed.emit();
      } else {
        this.result.set({ type: 'error', title: 'No Leads to Process', message: 'No unassigned leads found to process.' });
        this.resultOpen.set(true);
      }
    } catch (e: unknown) {
      const err = e as { error?: { message?: string } };
      this.result.set({
        type: 'error',
        title: 'Processing Failed',
        message: err.error?.message || 'Failed to process.',
      });
      this.resultOpen.set(true);
    } finally {
      this.saving.set(false);
    }
  }
}

@if (isOpen) {
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
    <div
      class="flex max-h-[90vh] w-full max-w-2xl flex-col overflow-hidden rounded-xl border border-gray-200 bg-white shadow-2xl dark:border-slate-600/80 dark:bg-slate-900 dark:shadow-black/40"
      role="dialog"
      aria-modal="true"
      aria-labelledby="auto-assign-title"
    >
      <!-- Header -->
      <div class="flex shrink-0 items-center justify-between border-b border-gray-200 px-6 py-5 dark:border-slate-600/80">
        <div class="flex items-center gap-2">
          <svg
            class="h-5 w-5 shrink-0 text-primary-600 dark:text-primary-400"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"
            />
          </svg>
          <h3 id="auto-assign-title" class="text-lg font-semibold text-gray-900 dark:text-white">Auto Assignment Settings</h3>
        </div>
        <button
          type="button"
          (click)="close()"
          class="rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600 dark:hover:bg-slate-700 dark:hover:text-gray-200"
          aria-label="Close"
        >
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Scrollable body -->
      <div class="min-h-0 flex-1 overflow-y-auto px-6 py-6">
        @if (loading()) {
          <div class="flex flex-col items-center justify-center py-12">
            <div
              class="h-8 w-8 animate-spin rounded-full border-4 border-primary-500 border-t-transparent"
              aria-hidden="true"
            ></div>
            <p class="mt-3 text-sm text-gray-600 dark:text-slate-400">Loading settings…</p>
          </div>
        } @else {
          <div class="space-y-8">
            <!-- How to use -->
            <div class="rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-950/40">
              <h4 class="mb-2 text-sm font-medium text-blue-900 dark:text-blue-200">How to Use Auto Assignment</h4>
              <ol class="list-inside list-decimal space-y-1 text-xs text-blue-800 dark:text-blue-300">
                <li>Import your CSV files (with or without &quot;Assign To&quot; column)</li>
                <li>Configure assignments below (CSV file-specific or round-robin)</li>
                <li>Click &quot;Process Documents&quot; to assign all unassigned leads</li>
              </ol>
            </div>

            <!-- Employee availability -->
            <div>
              <h4 class="mb-1 text-sm font-medium text-gray-900 dark:text-white">Employee Availability</h4>
              <p class="mb-4 text-xs text-gray-600 dark:text-slate-400">
                Toggle employees on/off for auto-assignment. Disabled employees will be skipped in the rotation.
              </p>
              <div class="space-y-2">
                @for (u of eligibleUsers(); track u._id) {
                  <div
                    class="flex items-center justify-between rounded-lg border p-3 transition-colors"
                    [ngClass]="
                      isExcluded(u._id)
                        ? 'bg-gray-50 border-gray-200 dark:border-slate-600 dark:bg-slate-800'
                        : 'border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-950'
                    "
                  >
                    <div class="flex min-w-0 items-center">
                      <span
                        class="mr-3 h-2 w-2 shrink-0 rounded-full"
                        [class.bg-gray-400]="isExcluded(u._id)"
                        [class.bg-green-500]="!isExcluded(u._id)"
                        aria-hidden="true"
                      ></span>
                      <div class="min-w-0">
                        <p class="truncate text-sm font-medium text-gray-900 dark:text-white">{{ u.name }}</p>
                        <p class="truncate text-xs text-gray-600 dark:text-slate-400">{{ u.email }}</p>
                      </div>
                    </div>
                    <button
                      type="button"
                      (click)="toggleExcluded(u._id)"
                      class="shrink-0 rounded-full px-3 py-1 text-xs font-medium transition-colors"
                      [ngClass]="
                        isExcluded(u._id)
                          ? 'bg-gray-200 text-gray-800 hover:bg-gray-300 dark:bg-slate-600 dark:text-slate-200 dark:hover:bg-slate-500'
                          : 'bg-green-600 text-white hover:bg-green-700'
                      "
                    >
                      {{ isExcluded(u._id) ? 'Disabled' : 'Active' }}
                    </button>
                  </div>
                }
              </div>
              @if (eligibleUsers().length === 0) {
                <p class="py-4 text-center text-sm text-gray-500 dark:text-slate-500">No active employees found</p>
              }
            </div>

            <!-- Source-specific -->
            <div>
              <h4 class="mb-1 text-sm font-medium text-gray-900 dark:text-white">Source-Specific Assignments</h4>
              <p class="mb-4 text-xs text-gray-600 dark:text-slate-400">
                Assign specific sources to specific employees. These take priority over round-robin assignment.
              </p>
              <div class="space-y-2">
                @for (s of projectSources; track s._id) {
                  <div
                    class="flex flex-col gap-3 rounded-lg border border-gray-200 bg-white p-3 sm:flex-row sm:items-center sm:justify-between dark:border-slate-600 dark:bg-slate-800/50"
                  >
                    <div class="min-w-0 flex-1">
                      <p class="text-sm font-medium text-gray-900 dark:text-white">{{ s.name }}</p>
                      @if (sourceSubtitle(s)) {
                        <p class="mt-0.5 text-xs text-gray-600 dark:text-slate-400">{{ sourceSubtitle(s) }}</p>
                      }
                    </div>
                    <select
                      class="w-full shrink-0 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:ring-2 focus:ring-teal-500 sm:w-56 dark:border-slate-600 dark:bg-slate-900 dark:text-white"
                      [ngModel]="getSourceAssign(s.name)"
                      (ngModelChange)="setSourceAssign(s.name, $event)"
                      [ngModelOptions]="{ standalone: true }"
                    >
                      <option value="">Auto Assign (default)</option>
                      @for (u of eligibleUsers(); track u._id) {
                        <option [value]="u._id">{{ u.name }}</option>
                      }
                    </select>
                  </div>
                }
              </div>
              @if (projectSources.length === 0) {
                <p class="py-4 text-center text-sm text-gray-500 dark:text-slate-500">
                  No project sources found. Create sources first to assign them.
                </p>
              }
            </div>

            <!-- CSV file-specific -->
            <div>
              <h4 class="mb-1 text-sm font-medium text-gray-900 dark:text-white">CSV File-Specific Assignments</h4>
              <p class="mb-4 text-xs text-gray-600 dark:text-slate-400">
                Assign specific CSV files to specific employees. These take highest priority over source and round-robin
                assignments.
              </p>
              @if (csvFiles().length === 0) {
                <p class="py-4 text-center text-sm text-gray-500 dark:text-slate-500">
                  No CSV files imported yet. Import CSV files to assign them.
                </p>
              } @else {
                <div class="max-h-52 space-y-2 overflow-y-auto pr-1">
                  @for (f of csvFiles(); track f) {
                    <div
                      class="flex flex-col gap-3 rounded-lg border border-gray-200 bg-white p-3 sm:flex-row sm:items-center sm:justify-between dark:border-slate-600 dark:bg-slate-800/50"
                    >
                      <div class="min-w-0 flex-1">
                        <p class="truncate font-mono text-sm font-medium text-gray-900 dark:text-white" [title]="f">{{ f }}</p>
                      </div>
                      <select
                        class="w-full shrink-0 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:ring-2 focus:ring-teal-500 sm:w-56 dark:border-slate-600 dark:bg-slate-900 dark:text-white"
                        [ngModel]="getCsvAssign(f)"
                        (ngModelChange)="setCsvAssign(f, $event)"
                        [ngModelOptions]="{ standalone: true }"
                      >
                        <option value="">Auto Assign (default)</option>
                        @for (u of eligibleUsers(); track u._id) {
                          <option [value]="u._id">{{ u.name }}</option>
                        }
                      </select>
                    </div>
                  }
                </div>
              }
            </div>

            <!-- Priority info -->
            <div class="rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-950/40">
              <h4 class="mb-2 text-sm font-medium text-blue-900 dark:text-blue-200">Assignment Priority</h4>
              <ul class="space-y-1 text-xs text-blue-800 dark:text-blue-300">
                <li>• Priority 1: CSV file-specific assignments (highest priority)</li>
                <li>• Priority 2: Source-specific assignments</li>
                <li>• Priority 3: Round-robin assignment (if no specific assignment)</li>
                <li>• Disabled employees are automatically skipped in round-robin</li>
                <li>• Round-robin continues from where it left off</li>
              </ul>
            </div>
          </div>
        }
      </div>

      <!-- Footer -->
      <div
        class="flex shrink-0 flex-col gap-3 border-t border-gray-200 px-6 py-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-600/80"
      >
        <button
          type="button"
          (click)="close()"
          class="order-2 rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 sm:order-1 dark:border-slate-600 dark:text-slate-200 dark:hover:bg-slate-800"
        >
          Cancel
        </button>
        <div class="order-1 flex flex-wrap gap-2 sm:order-2 sm:justify-end">
          <button
            type="button"
            (click)="save()"
            [disabled]="saving() || loading()"
            class="rounded-md bg-gray-600 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {{ saving() ? 'Saving…' : 'Save Settings' }}
          </button>
          <button
            type="button"
            (click)="saveAndProcess()"
            [disabled]="saving() || loading()"
            class="rounded-md bg-primary-600 px-4 py-2 text-sm font-medium text-white hover:bg-primary-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {{ saving() ? 'Processing…' : 'Process Documents' }}
          </button>
        </div>
      </div>
    </div>
  </div>
}

@if (resultOpen()) {
  <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4">
    <div class="w-full max-w-md rounded-lg bg-white shadow-xl dark:bg-slate-900 dark:ring-1 dark:ring-slate-600">
      <h4
        class="border-b border-gray-200 px-6 py-4 text-lg font-semibold dark:border-slate-600"
        [class.text-green-700]="result().type === 'success'"
        [class.dark:text-green-400]="result().type === 'success'"
        [class.text-red-700]="result().type === 'error'"
        [class.dark:text-red-400]="result().type === 'error'"
      >
        {{ result().title }}
      </h4>
      <p class="px-6 py-4 text-sm text-gray-600 dark:text-slate-300">{{ result().message }}</p>
      <div class="flex justify-end border-t border-gray-200 px-6 py-4 dark:border-slate-600">
        <button
          type="button"
          (click)="resultOpen.set(false)"
          class="rounded-md bg-gray-200 px-4 py-2 text-sm font-medium text-gray-800 hover:bg-gray-300 dark:bg-slate-700 dark:text-white dark:hover:bg-slate-600"
        >
          OK
        </button>
      </div>
    </div>
  </div>
}

// client/src/components/AutoAssignmentModal.jsx
import React, { useState, useEffect } from 'react'
import { X, Users, CheckCircle, XCircle } from 'lucide-react'
import axios from 'axios'

const AutoAssignmentModal = ({ isOpen, onClose, users, projectSources = [] }) => {
  const [settings, setSettings] = useState(null)
  const [excludedEmployees, setExcludedEmployees] = useState([])
  const [sourceAssignments, setSourceAssignments] = useState([])
  const [csvFileAssignments, setCsvFileAssignments] = useState([])
  const [csvFiles, setCsvFiles] = useState([])
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [showResultModal, setShowResultModal] = useState(false)
  const [resultMessage, setResultMessage] = useState({ type: '', title: '', message: '' })

  useEffect(() => {
    if (isOpen) {
      fetchSettings()
      fetchCsvFiles()
    }
  }, [isOpen])

  const fetchSettings = async () => {
    setLoading(true)
    try {
      const response = await axios.get('/api/auto-assignment')
      setSettings(response.data)
      setExcludedEmployees(response.data.excludedEmployees.map(e => e._id))
      setSourceAssignments(response.data.sourceAssignments || [])
      setCsvFileAssignments(response.data.csvFileAssignments || [])
    } catch (error) {
      console.error('Error fetching auto-assignment settings:', error)
    } finally {
      setLoading(false)
    }
  }

  const fetchCsvFiles = async () => {
    try {
      const response = await axios.get('/api/auto-assignment/csv-files')
      setCsvFiles(response.data)
    } catch (error) {
      console.error('Error fetching CSV files:', error)
    }
  }

  const showResult = (type, title, message) => {
    setResultMessage({ type, title, message })
    setShowResultModal(true)
  }

  const handleSave = async () => {
    setSaving(true)
    try {
      await axios.put('/api/auto-assignment', {
        excludedEmployees,
        sourceAssignments,
        csvFileAssignments
      })
      showResult('success', 'Settings Saved', 'Auto-assignment settings have been saved successfully.')
    } catch (error) {
      console.error('Error saving auto-assignment settings:', error)
      showResult('error', 'Save Failed', error.response?.data?.message || 'Failed to save settings. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  const handleProcessDocuments = async () => {
    setSaving(true)
    try {
      // First save the settings
      await axios.put('/api/auto-assignment', {
        excludedEmployees,
        sourceAssignments,
        csvFileAssignments
      })

      // Then trigger the assignment process
      const response = await axios.post('/api/auto-assignment/process-unassigned')
      
      if (response.data.success) {
        const { assignedCount, failedCount } = response.data
        const message = failedCount > 0 
          ? `Successfully assigned ${assignedCount} lead(s). ${failedCount} lead(s) failed to assign.`
          : `Successfully assigned ${assignedCount} lead(s).`
        
        showResult('success', 'Processing Complete', message)
        
        // Refresh page after showing success
        setTimeout(() => {
          window.location.reload()
        }, 2000)
      } else {
        showResult('error', 'No Leads to Process', 'No unassigned leads found to process.')
      }
    } catch (error) {
      console.error('Error processing documents:', error)
      showResult('error', 'Processing Failed', error.response?.data?.message || 'Failed to process documents. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  const toggleEmployee = (employeeId) => {
    setExcludedEmployees(prev => {
      if (prev.includes(employeeId)) {
        return prev.filter(id => id !== employeeId)
      } else {
        return [...prev, employeeId]
      }
    })
  }

  const isEmployeeExcluded = (employeeId) => {
    return excludedEmployees.includes(employeeId)
  }

  const handleSourceAssignment = (sourceName, employeeId) => {
    setSourceAssignments(prev => {
      const existing = prev.find(sa => sa.sourceName === sourceName)
      if (existing) {
        if (employeeId === '') {
          // Remove assignment
          return prev.filter(sa => sa.sourceName !== sourceName)
        } else {
          // Update assignment
          return prev.map(sa => 
            sa.sourceName === sourceName 
              ? { ...sa, assignedTo: employeeId }
              : sa
          )
        }
      } else {
        // Add new assignment
        if (employeeId !== '') {
          return [...prev, { sourceName, assignedTo: employeeId }]
        }
        return prev
      }
    })
  }

  const getSourceAssignment = (sourceName) => {
    const assignment = sourceAssignments.find(sa => sa.sourceName === sourceName)
    return assignment?.assignedTo?._id || assignment?.assignedTo || ''
  }

  const handleCsvFileAssignment = (csvFileName, employeeId) => {
    setCsvFileAssignments(prev => {
      const existing = prev.find(ca => ca.csvFileName === csvFileName)
      if (existing) {
        if (employeeId === '') {
          // Remove assignment
          return prev.filter(ca => ca.csvFileName !== csvFileName)
        } else {
          // Update assignment
          return prev.map(ca => 
            ca.csvFileName === csvFileName 
              ? { ...ca, assignedTo: employeeId }
              : ca
          )
        }
      } else {
        // Add new assignment
        if (employeeId !== '') {
          return [...prev, { csvFileName, assignedTo: employeeId }]
        }
        return prev
      }
    })
  }

  const getCsvFileAssignment = (csvFileName) => {
    const assignment = csvFileAssignments.find(ca => ca.csvFileName === csvFileName)
    return assignment?.assignedTo?._id || assignment?.assignedTo || ''
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white dark:bg-gray-800 rounded-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto scrollbar-hide">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center">
            <Users className="h-5 w-5 text-primary-600 dark:text-primary-400 mr-2" />
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Auto Assignment Settings
            </h3>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {loading ? (
            <div className="text-center py-8">
              <div className="animate-spin h-8 w-8 border-4 border-primary-500 border-t-transparent rounded-full mx-auto"></div>
              <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">Loading settings...</p>
            </div>
          ) : (
            <>
              {/* Info Banner */}
              <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                <h4 className="text-sm font-medium text-blue-900 dark:text-blue-200 mb-2">
                  How to Use Auto Assignment
                </h4>
                <ol className="text-xs text-blue-800 dark:text-blue-300 space-y-1 list-decimal list-inside">
                  <li>Import your CSV files (with or without "Assign To" column)</li>
                  <li>Configure assignments below (CSV file-specific or round-robin)</li>
                  <li>Click "Process Documents" to assign all unassigned leads</li>
                </ol>
              </div>

              {/* Employee List */}
              <div>
                <h4 className="text-sm font-medium text-gray-900 dark:text-white mb-3">
                  Employee Availability
                </h4>
                <p className="text-xs text-gray-600 dark:text-gray-400 mb-4">
                  Toggle employees on/off for auto-assignment. Disabled employees will be skipped in the rotation.
                </p>
                
                <div className="space-y-2">
                  {users.filter(u => (u.role === 'sales' || u.role === 'mapping') && u.isActive).map((user) => {
                    const isExcluded = isEmployeeExcluded(user._id)
                    return (
                      <div
                        key={user._id}
                        className={`flex items-center justify-between p-3 rounded-lg border transition-colors ${
                          isExcluded
                            ? 'bg-gray-50 dark:bg-gray-700/30 border-gray-200 dark:border-gray-700'
                            : 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800'
                        }`}
                      >
                        <div className="flex items-center">
                          <div className={`w-2 h-2 rounded-full mr-3 ${
                            isExcluded ? 'bg-gray-400' : 'bg-green-500'
                          }`}></div>
                          <div>
                            <p className="text-sm font-medium text-gray-900 dark:text-white">
                              {user.name}
                            </p>
                            <p className="text-xs text-gray-600 dark:text-gray-400">
                              {user.email}
                            </p>
                          </div>
                        </div>
                        <button
                          onClick={() => toggleEmployee(user._id)}
                          className={`px-3 py-1 text-xs rounded-md transition-colors ${
                            isExcluded
                              ? 'bg-gray-200 dark:bg-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-500'
                              : 'bg-green-600 text-white hover:bg-green-700'
                          }`}
                        >
                          {isExcluded ? 'Disabled' : 'Active'}
                        </button>
                      </div>
                    )
                  })}
                </div>

                {users.filter(u => (u.role === 'sales' || u.role === 'mapping') && u.isActive).length === 0 && (
                  <p className="text-sm text-gray-500 dark:text-gray-400 text-center py-4">
                    No active employees found
                  </p>
                )}
              </div>

              {/* Source-Wise Assignment */}
              <div>
                <h4 className="text-sm font-medium text-gray-900 dark:text-white mb-3">
                  Source-Specific Assignments
                </h4>
                <p className="text-xs text-gray-600 dark:text-gray-400 mb-4">
                  Assign specific sources to specific employees. These take priority over round-robin assignment.
                </p>
                
                <div className="space-y-2">
                  {projectSources.map((source) => (
                    <div
                      key={source._id}
                      className="flex items-center justify-between p-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-700/50"
                    >
                      <div className="flex-1">
                        <p className="text-sm font-medium text-gray-900 dark:text-white">
                          {source.name}
                        </p>
                        {source.description && (
                          <p className="text-xs text-gray-600 dark:text-gray-400 mt-0.5">
                            {source.description}
                          </p>
                        )}
                      </div>
                      <select
                        value={getSourceAssignment(source.name)}
                        onChange={(e) => handleSourceAssignment(source.name, e.target.value)}
                        className="ml-4 px-3 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-teal-500"
                      >
                        <option value="">Auto Assign (default)</option>
                        {users.filter(u => (u.role === 'sales' || u.role === 'mapping') && u.isActive).map((user) => (
                          <option key={user._id} value={user._id}>
                            {user.name}
                          </option>
                        ))}
                      </select>
                    </div>
                  ))}
                </div>

                {projectSources.length === 0 && (
                  <p className="text-sm text-gray-500 dark:text-gray-400 text-center py-4">
                    No project sources found. Create sources first to assign them.
                  </p>
                )}
              </div>

              {/* CSV File-Wise Assignment */}
              <div>
                <h4 className="text-sm font-medium text-gray-900 dark:text-white mb-3">
                  CSV File-Specific Assignments
                </h4>
                <p className="text-xs text-gray-600 dark:text-gray-400 mb-4">
                  Assign specific CSV files to specific employees. These take highest priority over source and round-robin assignments.
                </p>
                
                <div className="space-y-2">
                  {csvFiles.map((csvFile) => (
                    <div
                      key={csvFile}
                      className="flex items-center justify-between p-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-700/50"
                    >
                      <div className="flex-1">
                        <p className="text-sm font-medium text-gray-900 dark:text-white font-mono">
                          {csvFile}
                        </p>
                      </div>
                      <select
                        value={getCsvFileAssignment(csvFile)}
                        onChange={(e) => handleCsvFileAssignment(csvFile, e.target.value)}
                        className="ml-4 px-3 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-teal-500"
                      >
                        <option value="">Auto Assign (default)</option>
                        {users.filter(u => (u.role === 'sales' || u.role === 'mapping') && u.isActive).map((user) => (
                          <option key={user._id} value={user._id}>
                            {user.name}
                          </option>
                        ))}
                      </select>
                    </div>
                  ))}
                </div>

                {csvFiles.length === 0 && (
                  <p className="text-sm text-gray-500 dark:text-gray-400 text-center py-4">
                    No CSV files imported yet. Import CSV files to assign them.
                  </p>
                )}
              </div>

              {/* Info Box */}
              <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                <h4 className="text-sm font-medium text-blue-900 dark:text-blue-200 mb-2">
                  Assignment Priority
                </h4>
                <ul className="text-xs text-blue-800 dark:text-blue-300 space-y-1">
                  <li>• Priority 1: CSV file-specific assignments (highest priority)</li>
                  <li>• Priority 2: Source-specific assignments</li>
                  <li>• Priority 3: Round-robin assignment (if no specific assignment)</li>
                  <li>• Disabled employees are automatically skipped in round-robin</li>
                  <li>• Round-robin continues from where it left off</li>
                </ul>
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="flex justify-between space-x-3 p-6 border-t border-gray-200 dark:border-gray-700">
          <button
            onClick={onClose}
            className="px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
          >
            Cancel
          </button>
          <div className="flex space-x-3">
            <button
              onClick={handleSave}
              disabled={saving || loading}
              className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {saving ? 'Saving...' : 'Save Settings'}
            </button>
            <button
              onClick={handleProcessDocuments}
              disabled={saving || loading}
              className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {saving ? 'Processing...' : 'Process Documents'}
            </button>
          </div>
        </div>
      </div>

      {/* Result Modal */}
      {showResultModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[60]">
          <div className="bg-white dark:bg-gray-800 rounded-lg w-full max-w-md shadow-2xl">
            {/* Header */}
            <div className={`flex items-center justify-between p-6 border-b ${
              resultMessage.type === 'success' 
                ? 'border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20' 
                : 'border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/20'
            }`}>
              <div className="flex items-center">
                {resultMessage.type === 'success' ? (
                  <CheckCircle className="h-6 w-6 text-green-600 dark:text-green-400 mr-3" />
                ) : (
                  <XCircle className="h-6 w-6 text-red-600 dark:text-red-400 mr-3" />
                )}
                <h3 className={`text-lg font-semibold ${
                  resultMessage.type === 'success'
                    ? 'text-green-900 dark:text-green-100'
                    : 'text-red-900 dark:text-red-100'
                }`}>
                  {resultMessage.title}
                </h3>
              </div>
              <button 
                onClick={() => {
                  setShowResultModal(false)
                  if (resultMessage.type === 'success' && resultMessage.title === 'Settings Saved') {
                    onClose()
                  }
                }}
                className={`${
                  resultMessage.type === 'success'
                    ? 'text-green-600 dark:text-green-400 hover:text-green-800 dark:hover:text-green-200'
                    : 'text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-200'
                }`}
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6">
              <p className="text-gray-700 dark:text-gray-300">
                {resultMessage.message}
              </p>
            </div>

            {/* Footer */}
            <div className="flex justify-end p-6 border-t border-gray-200 dark:border-gray-700">
              <button
                onClick={() => {
                  setShowResultModal(false)
                  if (resultMessage.type === 'success' && resultMessage.title === 'Settings Saved') {
                    onClose()
                  }
                }}
                className={`px-4 py-2 rounded-md ${
                  resultMessage.type === 'success'
                    ? 'bg-green-600 text-white hover:bg-green-700'
                    : 'bg-red-600 text-white hover:bg-red-700'
                }`}
              >
                OK
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default AutoAssignmentModal
