// client-new/src/app/features/mapping-management/mapping-management.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { EmployeeUser } from '../../models';
import { ConfirmDialogComponent } from '../../shared/confirm-dialog/confirm-dialog.component';

@Component({
  selector: 'app-mapping-management',
  standalone: true,
  imports: [CommonModule, FormsModule, ConfirmDialogComponent],
  templateUrl: './mapping-management.component.html',
})
export class MappingManagementComponent {
  private readonly http = inject(HttpClient);
  readonly users = signal<EmployeeUser[]>([]);
  readonly showModal = signal(false);
  readonly showImportModal = signal(false);
  readonly editingUser = signal<EmployeeUser | null>(null);
  readonly deleteConfirm = signal({ isOpen: false, userId: null as string | null, userName: '' });
  readonly searchQuery = signal('');
  readonly currentPage = signal(1);
  readonly itemsPerPage = 20;
  readonly refreshing = signal(false);
  readonly loading = signal(false);
  readonly csvFile = signal<File | null>(null);
  readonly importing = signal(false);
  readonly importResult = signal<{ success?: number; failed?: number; errors?: string[] } | null>(null);
  readonly errorModal = signal({ isOpen: false, title: '', message: '' });
  readonly successModal = signal({ isOpen: false, title: '', message: '' });
  formData = { name: '', email: '', password: '' };

  constructor() {
    void this.fetch();
  }

  async fetch(): Promise<void> {
    this.refreshing.set(true);
    try {
      const all = await firstValueFrom(this.http.get<EmployeeUser[]>('/api/users'));
      this.users.set(all.filter((u) => u.role === 'mapping'));
    } catch (e: unknown) {
      this.errorModal.set({
        isOpen: true,
        title: 'Failed to Load',
        message: (e as { error?: { message?: string } })?.error?.message || 'Unable to fetch mapping users.',
      });
    } finally {
      this.refreshing.set(false);
    }
  }

  filtered(): EmployeeUser[] {
    const q = this.searchQuery().toLowerCase();
    return this.users().filter(
      (u) =>
        u.name.toLowerCase().includes(q) ||
        u.email.toLowerCase().includes(q) ||
        (u.mappingId && u.mappingId.toLowerCase().includes(q)),
    );
  }

  pageSlice(): EmployeeUser[] {
    const f = this.filtered();
    const s = (this.currentPage() - 1) * this.itemsPerPage;
    return f.slice(s, s + this.itemsPerPage);
  }

  totalPages(): number {
    return Math.max(1, Math.ceil(this.filtered().length / this.itemsPerPage));
  }

  openModal(u: EmployeeUser | null = null): void {
    if (u) {
      this.editingUser.set(u);
      this.formData = { name: u.name, email: u.email, password: '' };
    } else {
      this.editingUser.set(null);
      this.formData = { name: '', email: '', password: '' };
    }
    this.showModal.set(true);
  }

  async save(e: Event): Promise<void> {
    e.preventDefault();
    this.loading.set(true);
    try {
      const ed = this.editingUser();
      const payload = { ...this.formData, role: 'mapping' };
      if (ed) {
        await firstValueFrom(this.http.put(`/api/users/${ed._id}`, payload));
        this.successModal.set({ isOpen: true, title: 'User Updated', message: `${this.formData.name} updated.` });
      } else {
        const res = await firstValueFrom(this.http.post<{ mappingId?: string }>('/api/users', payload));
        this.successModal.set({
          isOpen: true,
          title: 'User Created',
          message: `${this.formData.name} created with Mapping ID: ${res.mappingId || ''}`,
        });
      }
      await this.fetch();
      this.showModal.set(false);
    } catch (e: unknown) {
      this.errorModal.set({
        isOpen: true,
        title: 'Error',
        message: (e as { error?: { message?: string } })?.error?.message || 'Save failed',
      });
    } finally {
      this.loading.set(false);
    }
  }

  async deleteUser(): Promise<void> {
    const d = this.deleteConfirm();
    if (!d.userId) return;
    try {
      await firstValueFrom(this.http.delete(`/api/users/${d.userId}`));
      this.successModal.set({ isOpen: true, title: 'Deleted', message: `${d.userName} deleted.` });
      await this.fetch();
    } catch (e: unknown) {
      this.errorModal.set({
        isOpen: true,
        title: 'Delete failed',
        message: (e as { error?: { message?: string } })?.error?.message || 'Unable to delete',
      });
    } finally {
      this.deleteConfirm.set({ isOpen: false, userId: null, userName: '' });
    }
  }

  async importCsv(e: Event): Promise<void> {
    e.preventDefault();
    const f = this.csvFile();
    if (!f) return;
    this.importing.set(true);
    this.importResult.set(null);
    const fd = new FormData();
    fd.append('csvFile', f);
    try {
      const res = await firstValueFrom(
        this.http.post<{ success?: number; failed?: number; errors?: string[] }>('/api/users/import-mapping', fd),
      );
      this.importResult.set(res);
      await this.fetch();
      this.csvFile.set(null);
    } catch (e: unknown) {
      this.errorModal.set({
        isOpen: true,
        title: 'Import Failed',
        message: (e as { error?: { message?: string } })?.error?.message || 'Import failed',
      });
    } finally {
      this.importing.set(false);
    }
  }

  prevPage(): void {
    this.currentPage.update((p) => Math.max(1, p - 1));
  }

  nextPage(): void {
    this.currentPage.update((p) => Math.min(this.totalPages(), p + 1));
  }
}

<div class="space-y-6">
  <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
    <div>
      <h2 class="text-lg font-semibold text-gray-900 dark:text-white">Mapping Management</h2>
      <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">Manage mapping team members and their login credentials</p>
    </div>
    <div class="flex flex-wrap gap-3">
      <button
        type="button"
        (click)="fetch()"
        [disabled]="refreshing()"
        class="flex items-center rounded-lg bg-gray-600 px-4 py-2 text-white hover:bg-gray-700 disabled:cursor-not-allowed disabled:opacity-50"
        title="Refresh mapping users"
      >
        <svg class="mr-2 h-4 w-4" [class.animate-spin]="refreshing()" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
        </svg>
        Refresh
      </button>
      <button
        type="button"
        (click)="showImportModal.set(true)"
        class="flex items-center rounded-lg bg-green-600 px-4 py-2 text-white hover:bg-green-700"
      >
        <svg class="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
        </svg>
        Import CSV
      </button>
      <button
        type="button"
        (click)="openModal(null)"
        class="flex items-center rounded-lg bg-primary-600 px-4 py-2 text-white hover:bg-primary-700"
      >
        <svg class="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
        </svg>
        Add Mapping User
      </button>
    </div>
  </div>

  <div class="relative">
    <svg class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
    <input
      type="text"
      placeholder="Search mapping users by name, email, or mapping ID..."
      [value]="searchQuery()"
      (input)="searchQuery.set($any($event.target).value); currentPage.set(1)"
      class="w-full rounded-lg border border-gray-300 bg-white py-2 pl-10 pr-4 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500"
    />
  </div>

  <div class="rounded-lg border border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-800">
    <div class="overflow-x-auto scrollbar-hide">
      <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
        <thead class="bg-gray-50 dark:bg-gray-700">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-gray-300">Mapping ID</th>
            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-gray-300">Name</th>
            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-gray-300">Email</th>
            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-gray-300">Status</th>
            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-gray-300">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200 bg-white dark:divide-gray-700 dark:bg-gray-800">
          @for (u of pageSlice(); track u._id) {
            <tr class="hover:bg-gray-50 dark:hover:bg-gray-700">
              <td class="whitespace-nowrap px-6 py-4">
                @if (u.mappingId) {
                  <span class="rounded px-2 py-1 text-xs font-mono text-purple-800 dark:text-purple-200 bg-purple-100 dark:bg-purple-900/20">
                    {{ u.mappingId }}
                  </span>
                } @else {
                  <span class="text-xs italic text-gray-400 dark:text-gray-500">Generating...</span>
                }
              </td>
              <td class="whitespace-nowrap px-6 py-4 text-sm font-medium text-gray-900 dark:text-white">{{ u.name }}</td>
              <td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500 dark:text-gray-400">{{ u.email }}</td>
              <td class="whitespace-nowrap px-6 py-4">
                <span
                  class="rounded-full px-2 py-1 text-xs"
                  [ngClass]="u.isActive ? 'bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-200' : 'bg-red-100 text-red-800 dark:bg-red-900/20 dark:text-red-200'"
                >
                  {{ u.isActive ? 'Active' : 'Inactive' }}
                </span>
              </td>
              <td class="whitespace-nowrap px-6 py-4 text-sm font-medium">
                <div class="flex space-x-2">
                  <button
                    type="button"
                    (click)="openModal(u)"
                    class="text-primary-600 hover:text-primary-900 dark:text-primary-400 dark:hover:text-primary-300"
                    title="Edit user"
                  >
                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                    </svg>
                  </button>
                  <button
                    type="button"
                    (click)="deleteConfirm.set({ isOpen: true, userId: u._id, userName: u.name })"
                    class="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                    title="Delete user"
                  >
                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.11 0 00-7.5 0" />
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          } @empty {
            <tr>
              <td colspan="5" class="px-6 py-8 text-center text-sm text-gray-500 dark:text-gray-400">
                {{ searchQuery() ? 'No mapping users found matching your search' : 'No mapping users yet' }}
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>

  @if (totalPages() > 1) {
    <div class="flex items-center justify-between border-t border-gray-200 pt-4 dark:border-gray-700">
      <div class="text-sm text-gray-700 dark:text-gray-300">
        Showing {{ ((currentPage() - 1) * itemsPerPage) + 1 }} to {{ currentPage() * itemsPerPage < filtered().length ? currentPage() * itemsPerPage : filtered().length }} of {{ filtered().length }} mapping users
      </div>
      <div class="flex space-x-2">
        <button
          type="button"
          (click)="prevPage()"
          [disabled]="currentPage() === 1"
          class="rounded-md border border-gray-300 px-3 py-1 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700"
        >
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" /></svg>
        </button>
        <span class="px-4 py-1 text-sm font-medium text-gray-700 dark:text-gray-300">Page {{ currentPage() }} of {{ totalPages() }}</span>
        <button
          type="button"
          (click)="nextPage()"
          [disabled]="currentPage() === totalPages()"
          class="rounded-md border border-gray-300 px-3 py-1 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700"
        >
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg>
        </button>
      </div>
    </div>
  }

  @if (showModal()) {
    <div class="fixed inset-0 z-[55] flex items-center justify-center bg-black bg-opacity-50 p-4">
      <div class="w-full max-w-md rounded-lg bg-white p-6 dark:bg-gray-800">
        <h3 class="mb-4 text-lg font-semibold text-gray-900 dark:text-white">{{ editingUser() ? 'Edit Mapping User' : 'Add Mapping User' }}</h3>

        <form (ngSubmit)="save($event)" class="space-y-4">
          <div>
            <label class="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Name *</label>
            <input type="text" required [(ngModel)]="formData.name" name="n" placeholder="Enter name" class="w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white" />
          </div>

          <div>
            <label class="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Email *</label>
            <input type="email" required [(ngModel)]="formData.email" name="em" placeholder="user@example.com" [disabled]="!!editingUser()" class="w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-gray-900 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-white" />
            @if (editingUser()) {
              <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Email cannot be changed</p>
            }
          </div>

          @if (editingUser()) {
            <div>
              <label class="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Mapping ID</label>
              <input type="text" [value]="editingUser()?.mappingId || 'N/A'" disabled class="w-full rounded-md border border-gray-300 bg-gray-100 px-3 py-2 font-mono text-sm text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white" />
              <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Mapping ID is auto-generated and cannot be changed</p>
            </div>
          }

          @if (!editingUser()) {
            <div>
              <label class="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Password *</label>
              <input type="password" required [(ngModel)]="formData.password" name="pw" placeholder="Enter password" class="w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white" />
            </div>
            <div class="rounded-md border border-blue-200 bg-blue-50 p-3 dark:border-blue-800 dark:bg-blue-900/20">
              <p class="text-xs text-blue-800 dark:text-blue-200"><strong>Note:</strong> A unique Mapping ID (VIB2-XXXX) will be automatically generated for this user.</p>
            </div>
          }

          <div class="flex justify-end space-x-3 pt-4">
            <button type="button" (click)="showModal.set(false)" class="rounded-md border border-gray-300 px-4 py-2 text-gray-700 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700">Cancel</button>
            <button type="submit" [disabled]="loading()" class="rounded-md bg-primary-600 px-4 py-2 text-white hover:bg-primary-700 disabled:opacity-50">
              {{ loading() ? 'Saving...' : editingUser() ? 'Update' : 'Create' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  }

  @if (showImportModal()) {
    <div class="fixed inset-0 z-[55] flex items-center justify-center bg-black bg-opacity-50 p-4">
      <div class="w-full max-w-lg rounded-lg bg-white p-6 dark:bg-gray-800">
        <h3 class="mb-4 text-lg font-semibold text-gray-900 dark:text-white">Import Mapping Users from CSV</h3>

        <form (ngSubmit)="importCsv($event)" class="space-y-4">
          <div>
            <label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">CSV File</label>
            <div class="relative">
              <input type="file" accept=".csv" (change)="csvFile.set($any($event.target).files?.[0] || null)" class="hidden" id="mapping-csv-file-input" required />
              <label for="mapping-csv-file-input" class="flex w-full cursor-pointer items-center justify-center rounded-lg border-2 border-dashed border-gray-300 bg-gray-50 px-4 py-3 transition-colors hover:border-primary-500 dark:border-gray-600 dark:bg-gray-700/50 dark:hover:border-primary-400">
                <svg class="mr-2 h-5 w-5 text-gray-400 dark:text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                </svg>
                <span class="text-sm text-gray-600 dark:text-gray-400">{{ csvFile()?.name || 'Choose CSV file or drag here' }}</span>
              </label>
            </div>
            <p class="mt-2 text-xs text-gray-500 dark:text-gray-400">CSV should have columns: name, email, password (Mapping ID will be auto-generated)</p>
          </div>

          @if (importResult()) {
            <div class="rounded-md p-4" [ngClass]="importResult()!.errors?.length ? 'bg-yellow-50 dark:bg-yellow-900/20' : 'bg-green-50 dark:bg-green-900/20'">
              <p class="text-sm font-medium text-gray-900 dark:text-white">Import Results:</p>
              <p class="text-sm text-gray-700 dark:text-gray-300">Successfully imported: {{ importResult()!.success || 0 }}</p>
              @if ((importResult()!.failed || 0) > 0) {
                <p class="text-sm text-gray-700 dark:text-gray-300">Failed: {{ importResult()!.failed }}</p>
              }
              @if (importResult()!.errors?.length) {
                <div class="mt-2">
                  <p class="text-xs font-medium text-gray-700 dark:text-gray-300">Errors:</p>
                  <ul class="list-inside list-disc text-xs text-gray-600 dark:text-gray-400">
                    @for (err of importResult()!.errors!.slice(0, 5); track $index) {
                      <li>{{ err }}</li>
                    }
                  </ul>
                </div>
              }
            </div>
          }

          <div class="flex justify-end space-x-3 pt-4">
            <button type="button" (click)="showImportModal.set(false); csvFile.set(null); importResult.set(null)" class="rounded-md border border-gray-300 px-4 py-2 text-gray-700 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700" [disabled]="importing()">Cancel</button>
            <button type="submit" [disabled]="importing() || !csvFile()" class="rounded-md bg-green-600 px-4 py-2 text-white hover:bg-green-700 disabled:opacity-50">
              {{ importing() ? 'Importing...' : 'Import' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  }

  <app-confirm-dialog
    [isOpen]="deleteConfirm().isOpen"
    (onClose)="deleteConfirm.set({ isOpen: false, userId: null, userName: '' })"
    (onConfirm)="deleteUser()"
    title="Delete Mapping User"
    [message]="'Are you sure you want to delete &quot;' + deleteConfirm().userName + '&quot;? This action cannot be undone.'"
    confirmText="Delete"
    cancelText="Cancel"
    variant="danger"
  />

  @if (errorModal().isOpen) {
    <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black bg-opacity-50 p-4">
      <div class="w-full max-w-md animate-fadeIn rounded-lg bg-white shadow-xl dark:bg-gray-800">
        <div class="p-6">
          <div class="flex items-start">
            <div class="flex-shrink-0">
              <div class="flex h-12 w-12 items-center justify-center rounded-full bg-red-100 dark:bg-red-900/20">
                <svg class="h-6 w-6 text-red-600 dark:text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0zM12 9v4m0 4h.01" />
                </svg>
              </div>
            </div>
            <div class="ml-4 flex-1">
              <h3 class="mb-2 text-lg font-semibold text-gray-900 dark:text-white">{{ errorModal().title }}</h3>
              <p class="text-sm text-gray-600 dark:text-gray-400">{{ errorModal().message }}</p>
            </div>
            <button type="button" (click)="errorModal.set({ isOpen: false, title: '', message: '' })" class="ml-4 flex-shrink-0 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300">
              <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
          </div>
        </div>
        <div class="flex justify-end rounded-b-lg bg-gray-50 px-6 py-4 dark:bg-gray-700/50">
          <button type="button" (click)="errorModal.set({ isOpen: false, title: '', message: '' })" class="rounded-md bg-red-600 px-4 py-2 text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500">Close</button>
        </div>
      </div>
    </div>
  }

  @if (successModal().isOpen) {
    <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black bg-opacity-50 p-4">
      <div class="w-full max-w-md animate-fadeIn rounded-lg bg-white shadow-xl dark:bg-gray-800">
        <div class="p-6">
          <div class="flex items-start">
            <div class="flex-shrink-0">
              <div class="flex h-12 w-12 items-center justify-center rounded-full bg-green-100 dark:bg-green-900/20">
                <svg class="h-6 w-6 text-green-600 dark:text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
            <div class="ml-4 flex-1">
              <h3 class="mb-2 text-lg font-semibold text-gray-900 dark:text-white">{{ successModal().title }}</h3>
              <p class="text-sm text-gray-600 dark:text-gray-400">{{ successModal().message }}</p>
            </div>
            <button type="button" (click)="successModal.set({ isOpen: false, title: '', message: '' })" class="ml-4 flex-shrink-0 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300">
              <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
          </div>
        </div>
        <div class="flex justify-end rounded-b-lg bg-gray-50 px-6 py-4 dark:bg-gray-700/50">
          <button type="button" (click)="successModal.set({ isOpen: false, title: '', message: '' })" class="rounded-md bg-green-600 px-4 py-2 text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500">OK</button>
        </div>
      </div>
    </div>
  }
</div>

// client/src/components/MappingManagement.jsx
import React, { useState, useEffect } from 'react'
import { Plus, Edit2, Trash2, Upload, Search, ChevronLeft, ChevronRight, RefreshCw, X, AlertCircle, CheckCircle } from 'lucide-react'
import axios from 'axios'
import ConfirmDialog from './ConfirmDialog'

const MappingManagement = () => {
  const [users, setUsers] = useState([])
  const [showModal, setShowModal] = useState(false)
  const [showImportModal, setShowImportModal] = useState(false)
  const [editingUser, setEditingUser] = useState(null)
  const [csvFile, setCsvFile] = useState(null)
  const [importing, setImporting] = useState(false)
  const [importResult, setImportResult] = useState(null)
  const [deleteConfirm, setDeleteConfirm] = useState({ isOpen: false, userId: null, userName: '' })
  const [searchQuery, setSearchQuery] = useState('')
  const [currentPage, setCurrentPage] = useState(1)
  const [itemsPerPage] = useState(20)
  const [refreshing, setRefreshing] = useState(false)
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' })
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' })
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: ''
  })
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    fetchMappingUsers()
  }, [])

  const fetchMappingUsers = async () => {
    try {
      setRefreshing(true)
      const response = await axios.get('/api/users')
      // Filter only mapping users
      const mappingUsers = response.data.filter(user => user.role === 'mapping')
      setUsers(mappingUsers)
    } catch (error) {
      console.error('Error fetching mapping users:', error)
      setErrorModal({
        isOpen: true,
        title: 'Failed to Load Mapping Users',
        message: error.response?.data?.message || 'Unable to fetch mapping users. Please try again.'
      })
    } finally {
      setRefreshing(false)
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)

    try {
      const userData = { ...formData, role: 'mapping' }
      
      if (editingUser) {
        await axios.put(`/api/users/${editingUser._id}`, userData)
        setSuccessModal({
          isOpen: true,
          title: 'User Updated',
          message: `${formData.name} has been successfully updated.`
        })
      } else {
        const response = await axios.post('/api/users', userData)
        setSuccessModal({
          isOpen: true,
          title: 'User Created',
          message: `${formData.name} has been successfully created with Mapping ID: ${response.data.mappingId}`
        })
      }
      
      fetchMappingUsers()
      setShowModal(false)
      resetForm()
    } catch (error) {
      console.error('Error saving mapping user:', error)
      setErrorModal({
        isOpen: true,
        title: editingUser ? 'Failed to Update User' : 'Failed to Create User',
        message: error.response?.data?.message || 'An error occurred while saving the mapping user. Please try again.'
      })
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async () => {
    try {
      await axios.delete(`/api/users/${deleteConfirm.userId}`)
      setSuccessModal({
        isOpen: true,
        title: 'User Deleted',
        message: `${deleteConfirm.userName} has been successfully deleted.`
      })
      fetchMappingUsers()
    } catch (error) {
      console.error('Error deleting mapping user:', error)
      setErrorModal({
        isOpen: true,
        title: 'Failed to Delete User',
        message: error.response?.data?.message || 'Unable to delete the mapping user. Please try again.'
      })
    }
  }

  const handleCsvImport = async (e) => {
    e.preventDefault()
    if (!csvFile) return

    setImporting(true)
    setImportResult(null)

    const formData = new FormData()
    formData.append('csvFile', csvFile)

    try {
      const response = await axios.post('/api/users/import-mapping', formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      })
      
      setImportResult(response.data)
      fetchMappingUsers()
      setCsvFile(null)
      
      if (response.data.success > 0 && response.data.failed === 0) {
        setSuccessModal({
          isOpen: true,
          title: 'Import Successful',
          message: `Successfully imported ${response.data.success} mapping user${response.data.success > 1 ? 's' : ''}.`
        })
        setTimeout(() => {
          setShowImportModal(false)
          setImportResult(null)
        }, 2000)
      } else if (response.data.failed > 0) {
        setTimeout(() => {
          setImportResult(null)
        }, 5000)
      }
    } catch (error) {
      console.error('Error importing CSV:', error)
      setErrorModal({
        isOpen: true,
        title: 'Import Failed',
        message: error.response?.data?.message || 'Failed to import CSV file. Please check the file format and try again.'
      })
      setImportResult({
        success: 0,
        failed: 0,
        errors: [error.response?.data?.message || 'Failed to import CSV']
      })
    } finally {
      setImporting(false)
    }
  }

  const resetForm = () => {
    setFormData({ name: '', email: '', password: '' })
    setEditingUser(null)
  }

  const openModal = (user = null) => {
    if (user) {
      setFormData({
        name: user.name,
        email: user.email,
        password: ''
      })
      setEditingUser(user)
    } else {
      resetForm()
    }
    setShowModal(true)
  }

  // Filter and paginate users
  const filteredUsers = users.filter(user => {
    const searchLower = searchQuery.toLowerCase()
    return (
      user.name.toLowerCase().includes(searchLower) ||
      user.email.toLowerCase().includes(searchLower) ||
      (user.mappingId && user.mappingId.toLowerCase().includes(searchLower))
    )
  })

  const totalPages = Math.ceil(filteredUsers.length / itemsPerPage)
  const startIndex = (currentPage - 1) * itemsPerPage
  const endIndex = startIndex + itemsPerPage
  const paginatedUsers = filteredUsers.slice(startIndex, endIndex)

  // Reset to page 1 when search changes
  useEffect(() => {
    setCurrentPage(1)
  }, [searchQuery])

  // Error Modal Component
  const ErrorModal = ({ isOpen, title, message, onClose }) => {
    if (!isOpen) return null

    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[60]">
        <div className="bg-white dark:bg-gray-800 rounded-lg w-full max-w-md shadow-xl animate-fadeIn">
          <div className="p-6">
            <div className="flex items-start">
              <div className="flex-shrink-0">
                <div className="w-12 h-12 rounded-full bg-red-100 dark:bg-red-900/20 flex items-center justify-center">
                  <AlertCircle className="h-6 w-6 text-red-600 dark:text-red-400" />
                </div>
              </div>
              <div className="ml-4 flex-1">
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                  {title}
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  {message}
                </p>
              </div>
              <button
                onClick={onClose}
                className="flex-shrink-0 ml-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
          </div>
          <div className="bg-gray-50 dark:bg-gray-700/50 px-6 py-4 rounded-b-lg flex justify-end">
            <button
              onClick={onClose}
              className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    )
  }

  // Success Modal Component
  const SuccessModal = ({ isOpen, title, message, onClose }) => {
    if (!isOpen) return null

    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[60]">
        <div className="bg-white dark:bg-gray-800 rounded-lg w-full max-w-md shadow-xl animate-fadeIn">
          <div className="p-6">
            <div className="flex items-start">
              <div className="flex-shrink-0">
                <div className="w-12 h-12 rounded-full bg-green-100 dark:bg-green-900/20 flex items-center justify-center">
                  <CheckCircle className="h-6 w-6 text-green-600 dark:text-green-400" />
                </div>
              </div>
              <div className="ml-4 flex-1">
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                  {title}
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  {message}
                </p>
              </div>
              <button
                onClick={onClose}
                className="flex-shrink-0 ml-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
          </div>
          <div className="bg-gray-50 dark:bg-gray-700/50 px-6 py-4 rounded-b-lg flex justify-end">
            <button
              onClick={onClose}
              className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500"
            >
              OK
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Mapping Management</h2>
          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
            Manage mapping team members and their login credentials
          </p>
        </div>
        <div className="flex space-x-3">
          <button
            onClick={fetchMappingUsers}
            disabled={refreshing}
            className="flex items-center px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            title="Refresh mapping users"
          >
            <RefreshCw className={`h-4 w-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
            Refresh
          </button>
          <button
            onClick={() => setShowImportModal(true)}
            className="flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
          >
            <Upload className="h-4 w-4 mr-2" />
            Import CSV
          </button>
          <button
            onClick={() => openModal()}
            className="flex items-center px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
          >
            <Plus className="h-4 w-4 mr-2" />
            Add Mapping User
          </button>
        </div>
      </div>

      {/* Search Bar */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
        <input
          type="text"
          placeholder="Search mapping users by name, email, or mapping ID..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
        />
      </div>

      {/* Table */}
      <div className="overflow-x-auto scrollbar-hide">
        <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead className="bg-gray-50 dark:bg-gray-700">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Mapping ID
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Name
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Email
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Status
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
            {paginatedUsers.length > 0 ? (
              paginatedUsers.map((user) => (
                <tr key={user._id}>
                  <td className="px-6 py-4 whitespace-nowrap">
                    {user.mappingId ? (
                      <span className="px-2 py-1 text-xs font-mono bg-purple-100 dark:bg-purple-900/20 text-purple-800 dark:text-purple-200 rounded">
                        {user.mappingId}
                      </span>
                    ) : (
                      <span className="text-xs text-gray-400 dark:text-gray-500 italic">Generating...</span>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                    {user.name}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                    {user.email}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 text-xs rounded-full ${
                      user.isActive 
                        ? 'bg-green-100 dark:bg-green-900/20 text-green-800 dark:text-green-200'
                        : 'bg-red-100 dark:bg-red-900/20 text-red-800 dark:text-red-200'
                    }`}>
                      {user.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex space-x-2">
                      <button
                        onClick={() => openModal(user)}
                        className="text-primary-600 dark:text-primary-400 hover:text-primary-900 dark:hover:text-primary-300"
                        title="Edit user"
                      >
                        <Edit2 className="h-4 w-4" />
                      </button>
                      <button
                        onClick={() => setDeleteConfirm({ 
                          isOpen: true, 
                          userId: user._id, 
                          userName: user.name 
                        })}
                        className="text-red-600 dark:text-red-400 hover:text-red-900 dark:hover:text-red-300"
                        title="Delete user"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={5} className="px-6 py-8 text-center text-sm text-gray-500 dark:text-gray-400">
                  {searchQuery ? 'No mapping users found matching your search' : 'No mapping users yet'}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between border-t border-gray-200 dark:border-gray-700 pt-4">
          <div className="text-sm text-gray-700 dark:text-gray-300">
            Showing {startIndex + 1} to {Math.min(endIndex, filteredUsers.length)} of {filteredUsers.length} mapping users
          </div>
          <div className="flex space-x-2">
            <button
              onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
              disabled={currentPage === 1}
              className="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <ChevronLeft className="h-4 w-4" />
            </button>
            <span className="px-4 py-1 text-sm font-medium text-gray-700 dark:text-gray-300">
              Page {currentPage} of {totalPages}
            </span>
            <button
              onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
              disabled={currentPage === totalPages}
              className="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      )}

      {/* Add/Edit Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[55]">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
              {editingUser ? 'Edit Mapping User' : 'Add Mapping User'}
            </h3>
            
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Name *
                </label>
                <input
                  type="text"
                  required
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Enter name"
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Email *
                </label>
                <input
                  type="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="user@example.com"
                  disabled={editingUser}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white disabled:opacity-50 disabled:cursor-not-allowed"
                />
                {editingUser && (
                  <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Email cannot be changed</p>
                )}
              </div>

              {editingUser && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Mapping ID
                  </label>
                  <input
                    type="text"
                    value={editingUser.mappingId || 'N/A'}
                    disabled
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-white font-mono text-sm"
                  />
                  <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Mapping ID is auto-generated and cannot be changed</p>
                </div>
              )}

              {!editingUser && (
                <>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Password *
                    </label>
                    <input
                      type="password"
                      required
                      value={formData.password}
                      onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                      placeholder="Enter password"
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    />
                  </div>
                  <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-md p-3">
                    <p className="text-xs text-blue-800 dark:text-blue-200">
                      <strong>Note:</strong> A unique Mapping ID (VIB2-XXXX) will be automatically generated for this user.
                    </p>
                  </div>
                </>
              )}
              
              <div className="flex justify-end space-x-3 pt-4">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50"
                >
                  {loading ? 'Saving...' : editingUser ? 'Update' : 'Create'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* CSV Import Modal */}
      {showImportModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[55]">
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-lg">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
              Import Mapping Users from CSV
            </h3>
            
            <form onSubmit={handleCsvImport} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  CSV File
                </label>
                <div className="relative">
                  <input
                    type="file"
                    accept=".csv"
                    onChange={(e) => setCsvFile(e.target.files[0])}
                    className="hidden"
                    id="mapping-csv-file-input"
                    required
                  />
                  <label
                    htmlFor="mapping-csv-file-input"
                    className="flex items-center justify-center w-full px-4 py-3 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg cursor-pointer hover:border-primary-500 dark:hover:border-primary-400 transition-colors bg-gray-50 dark:bg-gray-700/50"
                  >
                    <Upload className="h-5 w-5 text-gray-400 dark:text-gray-500 mr-2" />
                    <span className="text-sm text-gray-600 dark:text-gray-400">
                      {csvFile ? csvFile.name : 'Choose CSV file or drag here'}
                    </span>
                  </label>
                </div>
                <p className="mt-2 text-xs text-gray-500 dark:text-gray-400">
                  CSV should have columns: name, email, password (Mapping ID will be auto-generated)
                </p>
              </div>

              {importResult && (
                <div className={`p-4 rounded-md ${importResult.errors?.length > 0 ? 'bg-yellow-50 dark:bg-yellow-900/20' : 'bg-green-50 dark:bg-green-900/20'}`}>
                  <p className="text-sm font-medium text-gray-900 dark:text-white">
                    Import Results:
                  </p>
                  <p className="text-sm text-gray-700 dark:text-gray-300">
                    Successfully imported: {importResult.success || 0}
                  </p>
                  {importResult.failed > 0 && (
                    <p className="text-sm text-gray-700 dark:text-gray-300">
                      Failed: {importResult.failed}
                    </p>
                  )}
                  {importResult.errors?.length > 0 && (
                    <div className="mt-2">
                      <p className="text-xs font-medium text-gray-700 dark:text-gray-300">Errors:</p>
                      <ul className="text-xs text-gray-600 dark:text-gray-400 list-disc list-inside">
                        {importResult.errors.slice(0, 5).map((err, idx) => (
                          <li key={idx}>{err}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
              
              <div className="flex justify-end space-x-3 pt-4">
                <button
                  type="button"
                  onClick={() => {
                    setShowImportModal(false)
                    setCsvFile(null)
                    setImportResult(null)
                  }}
                  className="px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700"
                  disabled={importing}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={importing || !csvFile}
                  className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
                >
                  {importing ? 'Importing...' : 'Import'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={deleteConfirm.isOpen}
        onClose={() => setDeleteConfirm({ isOpen: false, userId: null, userName: '' })}
        onConfirm={handleDelete}
        title="Delete Mapping User"
        message={`Are you sure you want to delete "${deleteConfirm.userName}"? This action cannot be undone.`}
        confirmText="Delete"
        cancelText="Cancel"
        variant="danger"
      />

      {/* Error Modal */}
      <ErrorModal
        isOpen={errorModal.isOpen}
        title={errorModal.title}
        message={errorModal.message}
        onClose={() => setErrorModal({ isOpen: false, title: '', message: '' })}
      />

      {/* Success Modal */}
      <SuccessModal
        isOpen={successModal.isOpen}
        title={successModal.title}
        message={successModal.message}
        onClose={() => setSuccessModal({ isOpen: false, title: '', message: '' })}
      />
    </div>
  )
}

export default MappingManagement
