// client-new/src/app/features/reports/reports.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './reports.component.html',
})
export class ReportsComponent {
  private readonly http = inject(HttpClient);
  emailConfig = { email: '', appPassword: '', senderName: '' };
  reportSchedule = { daily: false, weekly: false, monthly: false, recipients: '' };
  loading = false;
  message: { type: string; text: string } | null = null;

  constructor() {
    void this.load();
  }

  async load(): Promise<void> {
    try {
      const ec = await firstValueFrom(this.http.get<{ email?: string; senderName?: string } | null>('/api/reports/email-config'));
      if (ec) {
        this.emailConfig = { email: ec.email || '', appPassword: '', senderName: ec.senderName || '' };
      }
    } catch {
      /* ignore */
    }
    try {
      const sch = await firstValueFrom(
        this.http.get<{ daily: boolean; weekly: boolean; monthly: boolean; recipients: string } | null>('/api/reports/schedule'),
      );
      if (sch) this.reportSchedule = { ...sch };
    } catch {
      /* ignore */
    }
  }

  async saveEmail(e: Event): Promise<void> {
    e.preventDefault();
    this.loading = true;
    this.message = null;
    try {
      await firstValueFrom(this.http.post('/api/reports/email-config', this.emailConfig));
      this.message = { type: 'success', text: 'Email configuration saved successfully!' };
      this.emailConfig.appPassword = '';
    } catch (err: unknown) {
      this.message = { type: 'error', text: (err as { error?: { message?: string } })?.error?.message || 'Failed to save email configuration' };
    } finally {
      this.loading = false;
    }
  }

  async saveSchedule(e: Event): Promise<void> {
    e.preventDefault();
    this.loading = true;
    this.message = null;
    try {
      await firstValueFrom(this.http.post('/api/reports/schedule', this.reportSchedule));
      this.message = { type: 'success', text: 'Report schedule saved successfully!' };
    } catch (err: unknown) {
      this.message = { type: 'error', text: (err as { error?: { message?: string } })?.error?.message || 'Failed to save report schedule' };
    } finally {
      this.loading = false;
    }
  }

  async generate(type: string): Promise<void> {
    this.loading = true;
    this.message = null;
    try {
      await firstValueFrom(this.http.post('/api/reports/generate', { type }));
      this.message = { type: 'success', text: `${type.charAt(0).toUpperCase() + type.slice(1)} report generated and sent!` };
    } catch (err: unknown) {
      this.message = { type: 'error', text: (err as { error?: { message?: string } })?.error?.message || 'Failed to generate report' };
    } finally {
      this.loading = false;
    }
  }
}

<div class="space-y-6">
  <div>
    <h2 class="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
      <svg class="h-7 w-7 mr-2 text-primary-600 dark:text-primary-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
      </svg>
      Reports & Email Configuration
    </h2>
    <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">
      Configure email settings and schedule automated reports
    </p>
  </div>

  @if (message?.text) {
    <div
      class="p-4 rounded-lg flex items-center gap-3"
      [ngClass]="message?.type === 'success' ? 'bg-green-50 dark:bg-green-900/20 text-green-800 dark:text-green-200 border border-green-200 dark:border-green-800' : 'bg-red-50 dark:bg-red-900/20 text-red-800 dark:text-red-200 border border-red-200 dark:border-red-800'"
    >
      @if (message?.type === 'success') {
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      } @else {
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0zM12 9v4m0 4h.01" />
        </svg>
      }
      <span>{{ message?.text }}</span>
    </div>
  }

  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
    <div class="flex items-center mb-4">
      <svg class="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Gmail SMTP Configuration</h3>
    </div>

    <form (ngSubmit)="saveEmail($event)" class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Sender Name</label>
        <input
          type="text"
          [(ngModel)]="emailConfig.senderName"
          name="senderName"
          placeholder="Presales Reports"
          class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
          required
        />
        <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">This name will appear as the sender in recipient inboxes</p>
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Gmail Address</label>
        <input
          type="email"
          [(ngModel)]="emailConfig.email"
          name="email"
          placeholder="your-email@gmail.com"
          class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
          required
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Gmail App Password</label>
        <input
          type="password"
          [(ngModel)]="emailConfig.appPassword"
          name="appPw"
          placeholder="Enter 16-character app password"
          class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
        />
        <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">
          Generate an app password from your Google Account settings.
          <a
            href="https://myaccount.google.com/apppasswords"
            target="_blank"
            rel="noopener noreferrer"
            class="text-primary-600 dark:text-primary-400 hover:underline ml-1"
          >
            Get App Password
          </a>
        </p>
      </div>

      <button
        type="submit"
        [disabled]="loading"
        class="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50 flex items-center gap-2"
      >
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
        {{ loading ? 'Saving...' : 'Save Configuration' }}
      </button>
    </form>
  </div>

  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
    <div class="flex items-center mb-4">
      <svg class="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Automated Report Schedule</h3>
    </div>

    <form (ngSubmit)="saveSchedule($event)" class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Report Frequency</label>
        <div class="space-y-2">
          <label class="flex items-center">
            <input type="checkbox" [(ngModel)]="reportSchedule.daily" name="daily" class="w-4 h-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500" />
            <span class="ml-2 text-sm text-gray-700 dark:text-gray-300">Daily Reports (sent every day at 9:00 AM)</span>
          </label>

          <label class="flex items-center">
            <input type="checkbox" [(ngModel)]="reportSchedule.weekly" name="weekly" class="w-4 h-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500" />
            <span class="ml-2 text-sm text-gray-700 dark:text-gray-300">Weekly Reports (sent every Monday at 9:00 AM)</span>
          </label>

          <label class="flex items-center">
            <input type="checkbox" [(ngModel)]="reportSchedule.monthly" name="monthly" class="w-4 h-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500" />
            <span class="ml-2 text-sm text-gray-700 dark:text-gray-300">Monthly Reports (sent on 1st of each month at 9:00 AM)</span>
          </label>
        </div>
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Report Recipients</label>
        <input
          type="text"
          [(ngModel)]="reportSchedule.recipients"
          name="recipients"
          placeholder="email1@example.com, email2@example.com"
          class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
        />
        <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">Separate multiple email addresses with commas</p>
      </div>

      <button
        type="submit"
        [disabled]="loading"
        class="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50 flex items-center gap-2"
      >
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-5 4v5m0 0l-3-3m3 3l3-3M9 5h6" />
        </svg>
        {{ loading ? 'Saving...' : 'Save Schedule' }}
      </button>
    </form>
  </div>

  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
    <div class="flex items-center mb-4">
      <svg class="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Generate Report Now</h3>
    </div>

    <p class="text-sm text-gray-600 dark:text-gray-400 mb-4">Generate and send a report immediately to configured recipients</p>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <button
        type="button"
        (click)="generate('daily')"
        [disabled]="loading"
        class="px-4 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2"
      >
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
        </svg>
        Daily Report
      </button>

      <button
        type="button"
        (click)="generate('weekly')"
        [disabled]="loading"
        class="px-4 py-3 bg-purple-600 text-white rounded-md hover:bg-purple-700 disabled:opacity-50 flex items-center justify-center gap-2"
      >
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
        </svg>
        Weekly Report
      </button>

      <button
        type="button"
        (click)="generate('monthly')"
        [disabled]="loading"
        class="px-4 py-3 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50 flex items-center justify-center gap-2"
      >
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
        </svg>
        Monthly Report
      </button>
    </div>
  </div>
</div>

// client/src/components/Reports.jsx
import React, { useState, useEffect } from 'react'
import { Mail, Send, Calendar, Clock, CheckCircle, AlertCircle, Settings } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import axios from 'axios'

const Reports = () => {
  const { user } = useAuth()
  const [emailConfig, setEmailConfig] = useState({
    email: '',
    appPassword: '',
    senderName: ''
  })
  const [reportSchedule, setReportSchedule] = useState({
    daily: false,
    weekly: false,
    monthly: false,
    recipients: ''
  })
  const [loading, setLoading] = useState(false)
  const [message, setMessage] = useState({ type: '', text: '' })

  useEffect(() => {
    fetchEmailConfig()
    fetchReportSchedule()
  }, [])

  const fetchEmailConfig = async () => {
    try {
      const response = await axios.get('/api/reports/email-config')
      if (response.data) {
        setEmailConfig({
          email: response.data.email || '',
          appPassword: '', // Never send password back
          senderName: response.data.senderName || ''
        })
      }
    } catch (error) {
      console.error('Error fetching email config:', error)
    }
  }

  const fetchReportSchedule = async () => {
    try {
      const response = await axios.get('/api/reports/schedule')
      if (response.data) {
        setReportSchedule(response.data)
      }
    } catch (error) {
      console.error('Error fetching report schedule:', error)
    }
  }

  const handleSaveEmailConfig = async (e) => {
    e.preventDefault()
    setLoading(true)
    setMessage({ type: '', text: '' })

    try {
      await axios.post('/api/reports/email-config', emailConfig)
      setMessage({ type: 'success', text: 'Email configuration saved successfully!' })
      // Clear password field after saving
      setEmailConfig(prev => ({ ...prev, appPassword: '' }))
    } catch (error) {
      setMessage({ 
        type: 'error', 
        text: error.response?.data?.message || 'Failed to save email configuration' 
      })
    } finally {
      setLoading(false)
    }
  }

  const handleSaveSchedule = async (e) => {
    e.preventDefault()
    setLoading(true)
    setMessage({ type: '', text: '' })

    try {
      await axios.post('/api/reports/schedule', reportSchedule)
      setMessage({ type: 'success', text: 'Report schedule saved successfully!' })
    } catch (error) {
      setMessage({ 
        type: 'error', 
        text: error.response?.data?.message || 'Failed to save report schedule' 
      })
    } finally {
      setLoading(false)
    }
  }

  const handleGenerateReport = async (type) => {
    setLoading(true)
    setMessage({ type: '', text: '' })

    try {
      await axios.post('/api/reports/generate', { type })
      setMessage({ type: 'success', text: `${type.charAt(0).toUpperCase() + type.slice(1)} report generated and sent!` })
    } catch (error) {
      setMessage({ 
        type: 'error', 
        text: error.response?.data?.message || 'Failed to generate report' 
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
          <Mail className="h-7 w-7 mr-2 text-primary-600 dark:text-primary-400" />
          Reports & Email Configuration
        </h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
          Configure email settings and schedule automated reports
        </p>
      </div>

      {/* Message Alert */}
      {message.text && (
        <div className={`p-4 rounded-lg flex items-center gap-3 ${
          message.type === 'success' 
            ? 'bg-green-50 dark:bg-green-900/20 text-green-800 dark:text-green-200 border border-green-200 dark:border-green-800' 
            : 'bg-red-50 dark:bg-red-900/20 text-red-800 dark:text-red-200 border border-red-200 dark:border-red-800'
        }`}>
          {message.type === 'success' ? (
            <CheckCircle className="h-5 w-5" />
          ) : (
            <AlertCircle className="h-5 w-5" />
          )}
          <span>{message.text}</span>
        </div>
      )}

      {/* Email Configuration */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
        <div className="flex items-center mb-4">
          <Settings className="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Gmail SMTP Configuration</h3>
        </div>
        
        <form onSubmit={handleSaveEmailConfig} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Sender Name
            </label>
            <input
              type="text"
              value={emailConfig.senderName}
              onChange={(e) => setEmailConfig({ ...emailConfig, senderName: e.target.value })}
              placeholder="Presales Reports"
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              required
            />
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              This name will appear as the sender in recipient inboxes
            </p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Gmail Address
            </label>
            <input
              type="email"
              value={emailConfig.email}
              onChange={(e) => setEmailConfig({ ...emailConfig, email: e.target.value })}
              placeholder="your-email@gmail.com"
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Gmail App Password
            </label>
            <input
              type="password"
              value={emailConfig.appPassword}
              onChange={(e) => setEmailConfig({ ...emailConfig, appPassword: e.target.value })}
              placeholder="Enter 16-character app password"
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            />
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              Generate an app password from your Google Account settings. 
              <a 
                href="https://myaccount.google.com/apppasswords" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-primary-600 dark:text-primary-400 hover:underline ml-1"
              >
                Get App Password
              </a>
            </p>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50 flex items-center gap-2"
          >
            <Settings className="h-4 w-4" />
            {loading ? 'Saving...' : 'Save Configuration'}
          </button>
        </form>
      </div>

      {/* Report Schedule */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
        <div className="flex items-center mb-4">
          <Calendar className="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Automated Report Schedule</h3>
        </div>

        <form onSubmit={handleSaveSchedule} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
              Report Frequency
            </label>
            <div className="space-y-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={reportSchedule.daily}
                  onChange={(e) => setReportSchedule({ ...reportSchedule, daily: e.target.checked })}
                  className="w-4 h-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500"
                />
                <span className="ml-2 text-sm text-gray-700 dark:text-gray-300">
                  Daily Reports (sent every day at 9:00 AM)
                </span>
              </label>

              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={reportSchedule.weekly}
                  onChange={(e) => setReportSchedule({ ...reportSchedule, weekly: e.target.checked })}
                  className="w-4 h-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500"
                />
                <span className="ml-2 text-sm text-gray-700 dark:text-gray-300">
                  Weekly Reports (sent every Monday at 9:00 AM)
                </span>
              </label>

              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={reportSchedule.monthly}
                  onChange={(e) => setReportSchedule({ ...reportSchedule, monthly: e.target.checked })}
                  className="w-4 h-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500"
                />
                <span className="ml-2 text-sm text-gray-700 dark:text-gray-300">
                  Monthly Reports (sent on 1st of each month at 9:00 AM)
                </span>
              </label>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Report Recipients
            </label>
            <input
              type="text"
              value={reportSchedule.recipients}
              onChange={(e) => setReportSchedule({ ...reportSchedule, recipients: e.target.value })}
              placeholder="email1@example.com, email2@example.com"
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            />
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              Separate multiple email addresses with commas
            </p>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50 flex items-center gap-2"
          >
            <Calendar className="h-4 w-4" />
            {loading ? 'Saving...' : 'Save Schedule'}
          </button>
        </form>
      </div>

      {/* Manual Report Generation */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
        <div className="flex items-center mb-4">
          <Clock className="h-5 w-5 text-gray-500 dark:text-gray-400 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Generate Report Now</h3>
        </div>

        <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
          Generate and send a report immediately to configured recipients
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button
            onClick={() => handleGenerateReport('daily')}
            disabled={loading}
            className="px-4 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2"
          >
            <Send className="h-4 w-4" />
            Daily Report
          </button>

          <button
            onClick={() => handleGenerateReport('weekly')}
            disabled={loading}
            className="px-4 py-3 bg-purple-600 text-white rounded-md hover:bg-purple-700 disabled:opacity-50 flex items-center justify-center gap-2"
          >
            <Send className="h-4 w-4" />
            Weekly Report
          </button>

          <button
            onClick={() => handleGenerateReport('monthly')}
            disabled={loading}
            className="px-4 py-3 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50 flex items-center justify-center gap-2"
          >
            <Send className="h-4 w-4" />
            Monthly Report
          </button>
        </div>
      </div>
    </div>
  )
}

export default Reports
